### ISSUE TITLE
Kubernetes: codecgen: produce consistent output on repeated runs 

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#101]
This is usability issue (not correctness one).
I observed that when I'm using codecgen, the output produced for a given file (I was using:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go
is non deterministic.
Few things that change:
1. constants "codecSelferC*" has different names, e.g.:

    codecSelferC_UTF85477         = 1
vs
  
     codecSelferC_UTF85165         = 1

2. ordering of generated function (and thus the names of variables they are using, because IIUC, you're using consecutive integers for variable names)

It would be very convenient if the output would be deterministic.

**Comment by ugorji** [comment]
Good point. It will definitely remove unnecessary git diff lines.

I will support an argument to codecgen which is used as the "random" string. You can pass it, and we will not try to generate a random one. The random one was important so that multiple codecgen files in the same directory do not cause duplicate variables.

**Comment by wojtek-t** [comment]
SGTM - thanks!

**Comment by ugorji** [comment]
@wojtek-t  Fixed.

Please re-get and re-install codecgen, as the command parameters have now been updated.

**Comment by wojtek-t** [comment]
@ugorji - this fixed the first problem I mentioned.

Is it posible also to make the order of functions to be deterministic?

**Comment by ugorji** [comment]
@wojtek-t Please try now. 

I tested it out, running twice, and comparing for diffs. Result: No diffs.

**Comment by ugorji** [comment]
@wojtek-t work well for you?

**Comment by wojtek-t** [comment]
sorry  - I'm already OOO and I'm not able to check it now. Will take a look after vacation.

**Comment by wojtek-t** [comment]
Hi again,
 I've finally managed to check it and it seems there is one more issue that I observe regarding this.
Basically there is "if false" statement in the init() function and this is non-deterministic. The example diff is here:

wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes/pkg/api/v1$ git diff
diff --git a/pkg/api/v1/types.generated.go b/pkg/api/v1/types.generated.go
index c955369..e7cc51e 100644
--- a/pkg/api/v1/types.generated.go
+++ b/pkg/api/v1/types.generated.go
@@ -42,13 +42,13 @@ func init() {
                panic(err)
        }
        if false { // reference the types, but skip this branch at build/run time
-               var v0 time.Time
-               var v1 pkg3_resource.Quantity
-               var v2 pkg4_inf.Dec
-               var v3 pkg5_util.IntOrString
-               var v4 pkg6_runtime.RawExtension
-               var v5 pkg1_types.UID
-               var v6 pkg2_unversioned.Time

+               var v0 pkg4_inf.Dec
+               var v1 pkg5_util.IntOrString
+               var v2 pkg6_runtime.RawExtension
+               var v3 pkg1_types.UID
+               var v4 pkg2_unversioned.Time
+               var v5 time.Time
+               var v6 pkg3_resource.Quantity
                _, _, _, _, _, _, _ = v0, v1, v2, v3, v4, v5, v6
        }

**Comment by wojtek-t** [comment]
@ugorji - friendly ping - can you please take a look?

**Comment by ugorji** [comment]
@wojtek-t let me know soonest how that works for you. I will be shifting from codec work soon. 

My tests show consistent output, but I'm not triggering as many code paths as you are.

**Comment by wojtek-t** [comment]
@ugorji - will check it tomorrow and will let you know. Thanks!

**Comment by wojtek-t** [comment]
@ugorji - thanks - it seems to work fine now

**Comment by ugorji** [comment]
Fully fixed now.
