### ISSUE TITLE
Codecgen and GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by szank** [ugorji/go#102]
Hi, I am have GO15VENDOREXPERIMENT flag set to 1. All my dependencies are in the {project}/vendor directory

When I am using codecgen, the resulting file import clause looks like this: 
```
import (
	codec1978 "bitbucket.org/{our_project_dir}/vendor/github.com/ugorji/go/codec"
	"errors"
	"fmt"
	"reflect"
	"runtime"
	"time"
)
```

This is not right, and the `go build` is complaining. Can you please fix this issue? Calling
`codecgen -c "github.com/ugorji/go/codec"` didn't help either. 

It is giving us some trouble, because we are running a build script, regenerating the encoding/decoding files every time. We can't change the import path manually every time. 

Best regards, 
Maciej

EDIT: 
I did track the issue to the gen.go file: 
```
func Gen(w io.Writer, buildTags, pkgName, uid string, useUnsafe bool, typ ...reflect.Type) {
...
	// gather imports first:
	x.cp = reflect.TypeOf(x).PkgPath() // return  "bitbucket.org/{our_project_dir}/vendor/github.com/ugorji/go/codec"
...
}
```

The easiest solution is to run regex to check if the /vendor dir is used, and remove it and everything before from the string. 
I will file an issue on the golang repo also, in the PkgPath() documentation, they state: 

  // PkgPath returns a named type's package path, that is, the import path
        // that uniquely identifies the package, such as "encoding/base64".
        // If the type was predeclared (string, error) or unnamed (*T, struct{}, []int),
        // the package path will be the empty string.
        PkgPath() string

This looks like a bug

**Comment by szank** [comment]
I got response from the golang team : 
https://github.com/golang/go/issues/12739
It looks like they don't want to change the PkgPath() behaviour. 
I would suggest either taking another command line argument for the codecgen tool, or using regex to strip the results of PkgPath() call.

**Comment by ugorji** [comment]
I wouldn't say "they don't want to change it". Minux has an opinion but I don't think he has the full picture. I would wait for Russ to weigh in after he returns from vacation.

At the same time, I may consider doing something to work around this "bug". It's not sufficient to fix it for codec import path, because any other "vendored" package you use in your types could trigger this misbehaviour also. 

I will follow up soon.
