### ISSUE TITLE
Canonical mode doesn’t sort keys lexicographically when encoding msgpack

### ISSUE THREAD

**Issue by Sidnicious** [ugorji/go#103]
When the `Canonical` flag is on, the keys of a map are sorted — after being encoded. In msgpack, encoded values include leading format bytes.

For example, a map of strings ends up being sorted by *length*, not by the string itself.

**Comment by Sidnicious** [comment]
Hmm, I see that canonical mode was introduced to support CBOR in #56, where this is the correct behavior. [Keybase](https://keybase.io/docs/api/1.0/canonical_packings) uses lexicographic ordering for JSON and msgpack — not sure what the right solution is.

**Comment by ugorji** [comment]
Canonical mode makes no guarantees about natural ordering e.g. sort alphabetically for strings, sort in ascending order for numbers, etc.

It just guarantees that a value will always be encoded in the same way. The "sanest" way to support that without knowledge of the types, is to encode to a []byte off-band, and then sort the bytes lexicographically. 

I don't think there's anything to fix here.

**Comment by Sidnicious** [comment]
Fair enough. It's not the behavior we want, but the behavior you chose definitely makes more sense from an implementation/speed standpoint. Thanks!
