### ISSUE TITLE
msgpack error messages

### ISSUE THREAD

**Issue by juanolon** [ugorji/go#106]
Hi
how can i catch/read msg-pack error messages. from the spec, it should be the 3th element on the response.see: https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md#response-message

thanks

**Comment by ugorji** [comment]
That is msgpack rpc.

I think you are conflating things.

**Comment by ugorji** [comment]
Please respond if theres any clarification

**Comment by juanolon** [comment]
hi,
yep, i'm a little confuse now. doesn't this library offers a handler for Msgpack, which i can use within the std lib net/rpc from go?

https://github.com/ugorji/go/blob/master/codec/msgpack.go#L702

how is this not the same as https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md ?

greetz
