### ISSUE TITLE
Syntax error during build

### ISSUE THREAD

**Issue by justinruggles** [ugorji/go#108]
```
# github.com/ugorji/go/codec
src/github.com/ugorji/go/codec/fast-path.generated.go:1824: v declared and not used
```

**Comment by jonnenauha** [comment]
Yep same here.

**Comment by ugorji** [comment]
I don't see how that could happen. Please do some debugging on your end and let me know if i missed something. On my end, it all compiles and works fine.

**Comment by justinruggles** [comment]
It happens with go1.4.3 but not with go1.5.1.

**Comment by ugorji** [comment]
I don't understand the error. Can you could help me understand why is happening?

**Comment by justinruggles** [comment]
It broke in https://github.com/ugorji/go/commit/5d8e71f2040f1161ca038d1f91f9dcfd5e277294. The generated code does look fine from what I can tell, so it's possibly a Go compiler bug. I've tried to make a simplified test case to reproduce the issue, but I can't. This is quite bad for me since I cannot upgrade my whole stack to go1.5 yet due to changes in GC interaction with cgo.

**Comment by ugorji** [comment]
That sucks. And I don't know what to do about it. You should at least file a bug or start a conversation on golang-nuts.

**Comment by ugorji** [comment]
This does not seem like a go-codec issue, so I plan to close it. Let me know if you have any objections.

**Comment by hkjn** [comment]
We are also impacted by this, via a [transitive dependency](https://github.com/coreos/go-etcd/blob/2038b5942e8e7f4f244729ff9353afab8ba11afc/etcd/response.go#L10) in `github.com/coreos/go-etcd/etcd` (which we do need).

Agreed that finding a minimal repro case and filing a bug against the Go team for 1.4 is the right course, and that upgrading to Go 1.5 seems to fix the issue, but like others we have issues still keeping us on Go 1.4, so if you'd consider holding back the commit that breaks the build for Go 1.4 compilers (despite it clearly not being a bug in your package) that would be much appreciated.

If you want a way to test this and have `docker` set up somewhere, this will work:
```
docker run -it golang:1.4.2 go get github.com/ugorji/go/codec
# github.com/ugorji/go/codec
src/github.com/ugorji/go/codec/fast-path.generated.go:1824: v declared and not used
```

Thanks in advance!

**Comment by hkjn** [comment]
FYI I sent an email to golang-nuts@googlegroups.com describing the issue, however I'm not sure if I posted there before, so it might be stuck in moderation queue for up to 24 hours.

**Comment by wojtek-t** [comment]
@ugorji - this bug unfortunately makes ugorji unsable in different projects (like Kubernetes) where we need to support Go 1.4
Is it possibly to revert that commit that broke this?

**Comment by ugorji** [comment]
Oh dang! That's not good.

Let me setup go 1.4 and see if I can workaround the bug within an hour or so. If I can't, I will rollback to a good state, and wait till 1.4 fix is released.

**Comment by ugorji** [comment]
I reproduced it in go 1.4, and worked around it (see commit description). I will start doing a sanity test on go 1.4 before I push, just to be safe.

**Comment by wojtek-t** [comment]
That will be great - thanks!

**Comment by hkjn** [comment]
Cheers @ugorji!

I can confirm that the package now builds fine at `HEAD`:
```
$ docker run --rm -t golang:1.4.2 go get github.com/ugorji/go/codec # no output
```

**Comment by ugorji** [comment]
Great! Really weird issue! Glad there was a quick workaround.

**Comment by yangzhe1991** [comment]
Thank you very much!

**Comment by jonnenauha** [comment]
I thought I was crazy when noticed it did not build on my 1.4 build bot server but built fine on 1.5. Very strange, glad it got reported to the go team.

I fixed it quickly by vendoring the previous commit :P Any changes this repo could do tags or move daily devving to another branch than master? Sure its the first time this happened from my perspective but if mishaps breaks big project builds like kubernetes, its something that could trivially be fixed by giving people stable tags so people can use gopkg.in without vendoring.
