### ISSUE TITLE
Codecgen exists with status 2

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#109]
I was trying to generated the file using codecgen for:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/testing/types.go

However, what I get is

    wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes/pkg/storage/testing$ codecgen -d 1234 -o types.generated.go types.go 
    codecgen error: error running 'go run codecgen-main-1234.generated.go': exit status 2, console: # k8s.io/kubernetes/pkg/storage/testing
    ./codecgen-pkg-1234.generated.go:28: not enough arguments in call to codec.Gen

I looked into it a bit deeper and it seems that file that is generated in the meantime is incorrect. Basically I see the following line in the generated code:

     codec1978.Gen(&out, "", "testing", "1234", false, typs...)

For me it seems that there is one argument missing here. Changing it to:

     codec1978.Gen(&out, "", "testing", "1234", false, nil, typs...)

seems to fix the problem

@ugorji

**Comment by ugorji** [comment]
@wojtek-t You have to recreate codecgen install. I added one more parameter to the command line there. Sorry for the inconvenience.

**Comment by wojtek-t** [comment]
@ugorji - how should I recreate it? Do you have any instructions?

**Comment by ugorji** [comment]
give me a couple of minutes. Let me make sure there wasn't a missed file in the commit.

**Comment by ugorji** [comment]
Yes, just do one of these as appropriate.

```
go install github.com/ugorji/go/codec/codecgen
```
OR
```
go get -u github.com/ugorji/go/codec/codecgen
```

**Comment by wojtek-t** [comment]
Thanks that works. I was doing:

    go get -u github.com/ugorji/go/codec

instead of

    go get -u github.com/ugorji/go/codec/codecgen
