### ISSUE TITLE
Question: how to decode a CBOR bytestring into a Go struct with []byte?

### ISSUE THREAD

**Issue by stefanermens** [ugorji/go#110]
I'm writing some functions to handle incoming cbor messages. Most types are decoded without problems in the structs I defined in Go. However, cbor bytestrings (e.g. 0x42 0x04 0x08) won't decode into a []byte. I get the following error:
"only encoded map or array can be decoded into a slice"

Any suggestions on how to decode bytestrings?

**Comment by ugorji** [comment]
Please provide a complete reproducer as a main.go which can be run with "go run main.go". Also tell what you see and what you expect to see. 

Thanks.

**Comment by stefanermens** [comment]
Hi Ugorji,

Thanks for the quick reply. See below for a simple example.

I would expect the cbor string to be decoded in the msg structure, but instead I get the error message "no matching struct field found when decoding stream array at index 0". If I set ErrorIfNoField to false, then I don't get an error, but nothing seems to be decoded. 

Do you have any suggestions? Should I define the struct in different way? Or am I missing something else?

```
package main

import (
	"fmt"
	"github.com/ugorji/go/codec"
)

type msg struct {
	value uint
	bytestring []byte
}

func (m msg) String() (s string) {
	s = fmt.Sprintf("Value: %v\n", m.value)
	for i, b := range m.bytestring {
		s = s + fmt.Sprintf("Byte %v: %v\n", i, b)
	}	
	return
}

func main() {
	var decoded msg
	myHandle := new(codec.CborHandle)
	myHandle.DecodeOptions.ErrorIfNoField = true

	cbor := []byte{0x82, 0x05, 0x42, 0x04, 0x08}

	dec := codec.NewDecoderBytes(cbor, myHandle)
	err := dec.Decode(&decoded)
	
	if err != nil {
		fmt.Println("cbor decode error: " + err.Error())
	} else {
		fmt.Print(decoded.String())
	}
}
```

**Comment by ugorji** [comment]
You cannot decide into a non-exported field. That field is technically not even seen. Capitalize the first letter of the field name and you should be all set.

**Comment by stefanermens** [comment]
Thanks, that was a simple solution :)

Now I'm trying to get it to work with the cbor message I receive, containing an array of byte strings. See the code below.

I get the error message "only encoded map or array can be decoded into a struct"

Any ideas?

Btw. I also tried specifying the ArrayOfByteStrings as [][]byte. But that gave the same result.

````
package main

import (
	"fmt"
	"github.com/ugorji/go/codec"
)

type msg struct {
	Value              int
	ArrayOfByteStrings []ByteString
}

type ByteString struct {
	Bytes []byte
}

func (m msg) String() (s string) {
	s = fmt.Sprintf("Value: %v\n", m.Value)
	for i, b := range m.ArrayOfByteStrings {
		for j, c := range b.Bytes {
			s = s + fmt.Sprintf("Byte %v.%v: %v\n", i, j, c)
		}
	}
	return
}

func main() {
	var decoded msg
	myHandle := new(codec.CborHandle)
	myHandle.DecodeOptions.ErrorIfNoField = true

	cbor := []byte{0x05, 0x82, 0x42, 0x01, 0x02, 0x42, 0x03, 0x04}

	dec := codec.NewDecoderBytes(cbor, myHandle)
	err := dec.Decode(&decoded)

	if err != nil {
		fmt.Println("cbor decode error: " + err.Error())
	} else {
		fmt.Print(decoded.String())
	}
}
````

**Comment by stefanermens** [comment]
I found a working solution. The cbor message now matches with the structure I defined. Changes compared to the previous example:
- added the first 0x82
- changed the struct. It now uses a [][]byte instead of a sub struct. Using the struct from the previous example required an additional 0x81 for the ByteString struct.

Thank you for your help!

Btw. Maybe adding an index (the first byte that couldn't be decoded) to the error message would make it easier to solve problems like this.

````
package main

import (
	"fmt"
	"github.com/ugorji/go/codec"
)

type msg struct {
	Value              int
	ArrayOfByteStrings [][]byte
}

func (m msg) String() (s string) {
	s = fmt.Sprintf("Value: %v\n", m.Value)
	for i, b := range m.ArrayOfByteStrings {
		for j, c := range b {
			s = s + fmt.Sprintf("Byte %v.%v: %v\n", i, j, c)
		}
	}
	return
}

func main() {
	var decoded msg
	myHandle := new(codec.CborHandle)
	myHandle.DecodeOptions.ErrorIfNoField = true

	cbor := []byte{0x82, 0x05, 0x82, 0x42, 0x01, 0x02, 0x42, 0x03, 0x04}

	dec := codec.NewDecoderBytes(cbor, myHandle)
	err := dec.Decode(&decoded)

	if err != nil {
		fmt.Println("cbor decode error: " + err.Error())
	} else {
		fmt.Print(decoded.String())
	}
}
````

**Comment by ugorji** [comment]
Excellent. Your cbor message is an array of 2 values, the first being an integer, and the second being an array of binary data. It can be decoded into a []interface{}, a struct {int, [][]byte}. You should read the full documentation, to see how it all works. 'http://ugorji.net/blog/go-codec-primer

Glad you figured it out.
