### ISSUE TITLE
corrupted encoding 

### ISSUE THREAD

**Issue by alvarolm** [ugorji/go#116]
I'm trying to just encode and decode:

    type MyStruct struct {
        id   int
        user string
    }
    var encodeMe MyStruct
    encodeMe.user = "message"
    encodeMe.id = 2049

    var bytes []byte

    if err := codec.NewEncoderBytes(&bytes, &c.encoderHandle).Encode(encodeMe); err != nil {
        t.Error(err)
    }

    //codec.NewEncoderBytes(&bytes, &c.encoderHandle).MustEncode(encodeMe)

    fmt.Println("bytesLen", len(bytes))
    fmt.Println("just encoded:", encodeMe)
    fmt.Println("to:", bytes)

    var encodeMe2 MyStruct

    if err := codec.NewDecoderBytes(bytes, &c.encoderHandle).Decode(&encodeMe2); err != nil {
        t.Error(err)
    }

    //  codec.NewDecoderBytes(bytes, &c.encoderHandle).MustDecode(&encodeMe2)

    fmt.Println("are the same ?", encodeMe, encodeMe2)
outputs:

>bytesLen 1
>just encoded: {2049 message}
>to: [128]
>are the same ? {2049 message} {0 }

encoding the whole struct to one byte (?), then when decoding returns empty values, someone knows why ?

**Comment by ugorji** [comment]
Can you please create a reproducer, as a single file with a package main, or a test file. Also include the output, and the expected output. I can't understand what you are saying here.

**Comment by ugorji** [comment]
codec only looks at exported fields i.e. your fields must start with an uppercase character.
