### ISSUE TITLE
Unmarshal empty JSON array as new empty Go array

### ISSUE THREAD

**Issue by ascheglov** [ugorji/go#119]
The current behavior is that empty array decodes into `nil`:

    var a []int
    codec.NewDecoderBytes([]byte(`[]`), jsonHandle).Decode(&a)
    // a == nil

However it would be preferable if JSON `[]` would be unmarshaled into a new empty array, and JSON `null` would be unmarshaled into `nil`.

Of course that `a` array can be initialized as `[]int{}` beforehand, but in real-life examples it would be somewhere in `map[string]interface{}`, so it won't be possible to initialize it.

Although there isn't much difference between `nil` and empty array in Go, it may be important for proxying JSON somewhere else. It's kind of unexpected when Unmarshal+Marshal changes `[]` and `{}` to `null` everywhere.

So it would be great to have such option in `DecodeOptions`, for both arrays and maps.

**Comment by ugorji** [comment]
This was a bug in the fast-path. I have finally seen one of the ills of the naked return.

Fixed now. Thanks.
