### ISSUE TITLE
CBOR decoding error on deeply nested lists

### ISSUE THREAD

**Issue by dmaze** [ugorji/go#122]
I am implementing a server for pre-existing Python code that depends heavily on distinguishing Python list and tuple types in an over-the-wire CBOR representation, and represents tuples as a CBOR tagged CBOR array.  I've implemented a codec library extension to handle this, and it works well for most cases, but some specific cases of nested objects work badly.  More specifically, the Python object

```python
data = [([([])])]
```

encodes to CBOR correctly, but decoding the resulting byte string produces an empty list.  A more complete example is at https://gist.github.com/dmaze/be159301fac5007dda41

**Comment by ugorji** [comment]
Please write a full reproducer (either a test file or a file with a main method runnable via go run), and document expected output, and actual output. 

Makes it easier to reproduce, or clarify expectations.

**Comment by ugorji** [comment]
I see the gist now. Will review in next couple of days

**Comment by ugorji** [comment]
I don't think this is workable.

By definition, tags are used to define a value which can be represented via native constructs. For example, a PythonTuple can be defined only via a list of native types like numbers, strings, booleans, etc. This implicitly suggests that tags cannot be nested i.e. a PythonTuple cannot be represented as a list of PythonTuple. 

The way decoding works is that we will look up the tag, then decode the next value nakedly, then convert the nakedly decoded value into the type that the tag is mapped to.

There's no way to support nested values here, and by definition, they should not work.

**Comment by dmaze** [comment]
I don't think anything in CBOR prohibits nested tags.  Another example (that's actually an accepted standardized tag number) is [tag 27 for generic type-prefixed objects](http://cbor.schmorp.de/generic-object) which could readily have further embedded tagged objects; many of the extensions in the [IANA CBOR tag registry](http://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml) are oriented towards serializing arbitrary Perl objects.

At any rate, the behavior of the codec library is a little bit odd and inconsistent.  You get

```
decode(list(tuple)) = list(tuple)
decode(list(tuple(list))) = list(tuple(list))
decode(list(tuple(list(tuple)))) = list(tuple(list(tuple)))
decode(list(tuple(list(tuple(anything))))) = list()
```

If the library really needed to ban nested tagged objects it should do so consistently.  But I'll see if I can put together a PR for this.  (I think this case worked 2-3 weeks ago.)

**Comment by ugorji** [comment]
Can you do a decode(tuple(anything)).?

**Comment by dmaze** [comment]
Yes.  I have a larger version of this test if you're interested in it.  In the same way, working up from the bottom:

```
decode(tuple(anything)) = tuple(anything)
decode(list(tuple(anything))) = list(tuple(anything))
decode(tuple(list(tuple(anything))) = tuple(list(tuple(anything)))
decode(list(tuple(list(tuple(anything)))) = list()
```

In the previously-referenced gist, you can change the object tree and its reference CBOR encoding in the Data() function; for instance if it

```go
return cbor, listTupleV, listTupleD
```

(commenting out topV and topD) then the test will correctly round-trip `tuple(list(tuple(list())))`.

**Comment by dmaze** [comment]
The tuple extension turns out to be a red herring.  If the object is list(list(...)) nested at least 4 deep, it fails.  Replace the `Data()` function from my gist above with

```go
func Data() (cbor *codec.CborHandle, data []byte, obj interface{}) {
	cbor = new(codec.CborHandle)
	topV := []interface{}{}
	topD := []byte{0x80}
	for i := 0; i < 4; i++ {
		topV = []interface{}{topV}
		topD = append([]byte{0x81}, topD...)
	}

	return cbor, topD, topV
}
```

For a very hackish workaround, increasing the size of `decNaked.sa` from 4 to 8 will fix this specific test, but not the general issue.

I think what's going on is something like this: in `kInterfaceNaked()`, if you're decoding a `valueTypeArray`, it extends `n.ss` and then decodes into the (current) `n.ss`.  That recursive decode can extend the underlying array, possibly into new storage.  Then on return the decoder looks at (new) `n.ss[l]` for the result, but it's not there, because the slice moved, so you get the zero value for the slice.

This presumably also happens for all four of the object stacks, but I think this is otherwise limited to `kInterfaceNaked` and not any of the rest of the decode interface.

**Comment by ugorji** [comment]
Nice analysis. Love it - thanks. Let me look into this some more. We should
have a general solution.
