### ISSUE TITLE
MapBySlice regression

### ISSUE THREAD

**Issue by heavenlyhash** [ugorji/go#124]
`MapBySlice` functionality seems to have regressed...

- at 1a25ccb -- after this, it emits arrays; before it's still... well, in json, it's `{}`, but there's another issue...
- at f081086 -- between this and 1a25ccb, broken structures are emitted: they declare as maps, but are joined like slices e.g. in json `{"key", "value"}` when it should be `{"key":"value"}`
- and before that, it works fine

This shows up on the basic examples like

```
type X []interface{}
func (_ X) MapBySlice() { }
v := X{"key1", 1, "key2", 2, "key3", 3}
```

Let me know if I can offer more description to help debug :D

**Comment by ugorji** [comment]
I don't really understand.

Can you put a reproducer that I can run via "go run file.go" or "go test". Also surviving what the expected output is, and what the new output is. That will make it easier to debug and fix, without me having to infer or decipher what you are saying. Thanks.

**Comment by ugorji** [comment]
Without a reproducer, I will have to close this as cannot-reproduce. I will leave open for another 3 days.

**Comment by ugorji** [comment]
I have now reproduced the issue. Will follow up soon.

**Comment by heavenlyhash** [comment]
Sorry I didn't get a test to you before you beat me to it.  You're amazing :D

I pulled the changes into my project and can double confirm it works.  Thanks!
