### ISSUE TITLE
Decoding generic slice values to right types with Msgpack

### ISSUE THREAD

**Issue by luizdepra** [ugorji/go#125]
Hello,

I'm trying to encode and decode a slice of multiple types  ([]interface{} with ints, strings, etc), but int values are decode to int64. This is a normal behaviour or i'm doing something wrong?

	package main

	import (
		"bufio"
		"bytes"
		"fmt"
		"reflect"

		"github.com/ugorji/go/codec"
	)

	func main() {
		var one int = 1
		slice := []interface{}{one, "lol"}

		fmt.Println(reflect.TypeOf(slice[0]))

		handler := &codec.MsgpackHandle{RawToString: true}
		buffer := &bytes.Buffer{}
		writer := bufio.NewWriter(buffer)
		reader := bufio.NewReader(buffer)
		encoder := codec.NewEncoder(writer, handler)
		decoder := codec.NewDecoder(reader, handler)

		err := encoder.Encode(slice)
		if err != nil {
			panic(err)
		}
		writer.Flush()

		ret := []interface{}{}

		err = decoder.Decode(&ret)
		if err != nil {
			panic(err)
		}

		fmt.Println(reflect.TypeOf(ret[0]))
	}

This code prints:

	int
	int64

**Comment by ugorji** [comment]
It's normal. Msgpack doesn't store the type of a value. So when you encode a int, it encodes it to msgpack as an integer number. When you tell us to decode it into a interface{}, we will use a default int64 type. If you tell us to decode it into a *int, then we will decode it into that *int.
