### ISSUE TITLE
invalid character for package alias

### ISSUE THREAD

**Issue by agupt** [ugorji/go#126]
code generated by codecgen  fails to remove "-" char from package name when generating alias, as a result go fmt fails. 

If your go code imports a package with name "foo-boo" after running codecgen it generates a package alias with name 'pkg%d_foo-boo'. This result in `go fmt` failure which result in codecgen failing.

**Comment by ugorji** [comment]
Fixed by #53d1166d60e9c56aa8312d3d43e8e535d90211cb
