### ISSUE TITLE
exit status 1.  expected 'STRING', found '-'

### ISSUE THREAD

**Issue by futureskywei** [ugorji/go#130]
I have imported "github.com/fsouza/go-dockerclient"   in my type.go . then exe  the comand  ' codecgen -o type.generated.go type.go'  return exit status 1, console: panic: 15:8: expected 'STRING', found '-' .
That is to say every type.go have imported contain '-'  exe codecgen will return error.

**Comment by ugorji** [comment]
Please I need a reproducer.

Can you add a type.go, and I can try to reproducer and fix

**Comment by futureskywei** [comment]
package api

import (
	"k8s.io/kubernetes/pkg/api/unversioned"
	kapi "k8s.io/kubernetes/pkg/api"
	godockerclient "github.com/fsouza/go-dockerclient"
)

type NodeList struct {
	unversioned.TypeMeta `json:",inline"`
	unversioned.ListMeta `json:"metadata,omitempty"`
	Items []Node `json:"items,omitempty"`
}

type Node struct {
	unversioned.TypeMeta `json:",inline"`
	kapi.ObjectMeta      `json:"metadata,omitempty"`
	Spec NodeSpec      `json:"spec,omitempty"`
}

type NodeSpec struct {
	IP         string      `json:"ip,omitempty"`
	Components []Component `json:"compnents,omitempty"`
}

type Component struct {
	Name       string                    `json:"name,omitempty"`
	Version    string                    `json:"version,omitempty"`
	Config     godockerclient.Config       `json:"config,omitempty"`
	HostConfig godockerclient.HostConfig   `json:"hostconfig,omitempty"`
}

**Comment by ugorji** [comment]
I just ran this locally, and it worked fine. See generated file: https://gist.github.com/ugorji/19801dc6d42ee1975762

Please update your codecgen and retry.

```
go get -u github.com/ugorji/go/codec github.com/ugorji/go/codec/codecgen
```
