### ISSUE TITLE
possible memroy leak in fastPathT.DecMapIntfIntfV

### ISSUE THREAD

**Issue by tubzby** [ugorji/go#146]
Good project first ^_^

I have forked this project ,because i want to stick to a revision of git,not to the master head,because go get always use the most fresh code. I stick on thie revision: 1d5269

currently I made a tcp server, for each connection, start a routine to decode msgpack and then do my job.

But I found server programe crash with error: "fatal error: runtime: out of memory", so I watch my server program with go tool pprof http://host/debug/pprof/heap, and found something related to this lib,I generate a svg file here:

[click here](http://pan.baidu.com/s/1jHbiue6)

I have been thinking of check the latest source, but something is broken for Nested anonymous struct field. for ex:

`type struct A {
   AInt int
}

type struct B {
    A   // A will encode at end of struct B,  before revision 1d5269, A is encode first.
   B   int
   C strint
}`
Because my go program is talking to other python servers, the encoding order and decoding order should keep the same.

**Comment by ugorji** [comment]
I can't help you with a fix for an old revision. I can help you with a bug on the latest revision. 

I suggest you file a bug for the latest revision if there is a bug there, and we can get that fixed. To file that bug, please include a reproducer file, that I can run with "go test" or "go run", and state what you see, and then what you expect to see, and how that is different. I can then fix. Right now, I don't really understand what the Nested anonymous issue you allude to is.
