### ISSUE TITLE
codecgen: wrongly generated vendored import paths under Go 1.6

### ISSUE THREAD

**Issue by 2opremio** [ugorji/go#147]
When building (and invoking) codecgen with Go 1.6 on a package with vendored dependencies it generates import paths like: `github.com/weaveworks/scope/vendor/github.com/ugorji/go/codec` instead of `github.com/ugorji/go/codec`.

It works when setting `GO15VENDOREXPERIMENT=1` but this is not required with Go 1.6 

See https://golang.org/doc/go1.6#go_command :

> Go 1.6 keeps the vendoring support, no longer considered experimental, and enables it by default. It can be disabled explicitly by setting the GO15VENDOREXPERIMENT environment variable to 0. Go 1.7 will remove support for the environment variable.

**Comment by ugorji** [comment]
Thanks for the bug. Looking into it now.
