### ISSUE TITLE
Decoding into nil interface{} using Extension broken?

### ISSUE THREAD

**Issue by FreGalle** [ugorji/go#153]
The documentation mentions being able to decode into nil interfaces using extensions, but I can't seem to get that to work. WriteExt is being called, but ReadExt is never called and the decoder decodes into a RawExt.

Am I wrong in expecting this to work or is this not working correctly?

```go
type myType struct {
	a string
}

func (m myType) WriteExt(v interface{}) []byte {
	return []byte{2, 2, 2}
}

func (m myType) ReadExt(dst interface{}, src []byte) {
}

func main() {
	var t = reflect.TypeOf(myType{})
	var e myType

	var handle = new(codec.MsgpackHandle)
	handle.SetBytesExt(t, 1, e)

	var b = new(bytes.Buffer)
	encoder := codec.NewEncoder(b, handle)
	encoder.Encode(myType{"test"})

	var x interface{}
	decoder := codec.NewDecoder(b, handle)
	decoder.Decode(&x)

	log.Printf("%T %+v", x, x)
}
```

**Comment by ugorji** [comment]
I am very confused with your bug report:

- how do you know that ReadExt is not called?
- what is this snippet of code expected to do?

I just ran it, and realized that I have no clue what it is trying to do or show.

Please provide a more representative and complete program that illustrates what you see. It should state what you see, and what you expect to see when the program is run, and why what you see if wrong and what you expect to see is correct.

Thanks.

**Comment by FreGalle** [comment]
The expected behaviour would be to see an empty myType be printed out at the end of the program, but instead it prints out the resulting RawExt. I've adjusted the example slightly to reflect this.

Turns out it is not a bug, though. Setting `WriteExt` to `true` on the handle enables the expected behaviour. Should have read the documentation more thoroughly.

**Comment by ugorji** [comment]
Sounds good. Thanks. Closing now.
