### ISSUE TITLE
self-describing interface types like encoding/gob

### ISSUE THREAD

**Issue by dougnukem** [ugorji/go#154]
Is there some way to configure an extension (or maybe just need to implement a new handler) to encode interface types as self-describing concrete types to assist in automatic decoding. It'd be nice to have self-describing JSON format that could encode interface types and decode them automatically. It may require the JSONHandle to `Register(concreteType{})` as it's done in gob encoding.

This is how the `encoding/gob` library handles it:

- https://golang.org/pkg/encoding/gob/

> Interface values are transmitted as a string identifying the concrete type being sent (a name that must be pre-defined by calling Register), followed by a byte count of the length of the following data (so the value can be skipped if it cannot be stored), followed by the usual encoding of concrete (dynamic) value stored in the interface value. (A nil interface value is identified by the empty string and transmits no value.) Upon receipt, the decoder verifies that the unpacked concrete item satisfies the interface of the receiving variable.

## Motivating Example

- https://play.golang.org/p/RbQI3l8RD_
```go
package main

import (
	"encoding/gob"
	"fmt"
	"bytes"
)

type Runner interface {
	Run() (Runner, error)
}

type exampleRunner struct {
}

func (r exampleRunner) Run() (Runner, error) {
	fmt.Println("exampleRunner RUNNING")
	return r, nil
}

type RunManager struct {
	Current Runner
}

func main() {
	gob.Register(exampleRunner{})
	
	r := &RunManager{Current: exampleRunner{}}
	r.Current.Run()

	// encode to gob bytes
	b := bytes.NewBuffer(nil)
	encoder := gob.NewEncoder(b)

	encoder.Encode(r)
	

	decoder := gob.NewDecoder(b)

	var decodedR RunManager
	decoder.Decode(&decodedR)

	fmt.Printf("Decoded RunManager Current Runner: %T %#v\n", decodedR.Current, decodedR.Current)
	decodedR.Current.Run()
}
```

**Output**
```
exampleRunner RUNNING
Decoded RunManager Current Runner: main.exampleRunner main.exampleRunner{}
exampleRunner RUNNING

```

**Comment by ugorji** [comment]
There is no way. This is a gob feature that is not part of the supported codec formats.

**Comment by dougnukem** [comment]
That's why I was wondering if it could be an extension. I've almost got a working version of it, but there's an issue where the codec dying before it hits my `UpdateExt` with an error:

"cannot decode non-nil codec value into nil main.State"

Seems like if the Decoder could use reflection to assign the non-nil interface value to the type in the struct.

Something like this should work but it seems to be failing before I get to `UpdateExt()` 
```
var globalPkgSet = poly.PkgNameSet{}

type Serializable struct {
	Interface interface{}
}

// MarshalText marshals the object if it has been previously
// registered with RegisterSerializable
func (s Serializable) MarshalJSON() ([]byte, error) {
	for {
		s2, ok := s.Interface.(Serializable)

		if !ok {
			break
		}

		s = s2
	}

	return poly.MarshalJSON(globalPkgSet, s.Interface)
}

// UnmarshalText unmarshals the object if it has been previously
// registered with RegisterSerializable
func (s *Serializable) UnmarshalJSON(b []byte) error {
	return poly.UnmarshalJSON(globalPkgSet, b, &s.Interface)
}

type PolyExt struct{}

// ConvertExt called when Marshalling
func (x PolyExt) ConvertExt(v interface{}) interface{} {
	return Serializable{Interface: v}
}

// UpdateExt called when Unmarshalling
func (x PolyExt) UpdateExt(dest interface{}, v interface{}) {
	switch val := v.(type) {
	case Serializable:
		// Need to allocate pointers in destination
		destV := Indirect(reflect.ValueOf(dest), v == nil)
		Decode(destV.Interface(), val.Interface)
	}
}

// RegisterSerializable registers types to be wrapped in a
// self-describing Serializable
func RegisterSerializable(vals ...interface{}) {
	globalPkgSet.Register(vals...)
	polyExt := PolyExt{}
	for i := range vals {
		t := reflect.TypeOf(vals[i])
		JSONCodec.SetInterfaceExt(t, uint64(i), polyExt)
	}
}

```

**Comment by ugorji** [comment]
I'm still lost.

I think you lose me because you talk in terms of gob i.e. you talk in terms of a format that stores description of the type of entity. Most formats (specifically those supported by codec) do not do that i.e. json, cbor, msgpack, binc, etc. This is because they are language-agnostic.

For what you are trying to do, your options are to use a custom type and ConvertExt/UpdateExt. 

If you stick with that, then write a clear bug report, I can look into it. Please provide a more representative and complete program that illustrates what you see. It should state what you see, and what you expect to see when the program is run, and why what you see if wrong and what you expect to see is correct. It should also be easily runnable via go run main.go or go test, so I can quickly run it and reproduce your issue.

Thanks.
