### ISSUE TITLE
How do you decode an error?

### ISSUE THREAD

**Issue by sb10** [ugorji/go#155]
I'm trying to encode and decode a struct where one of the properties is an error. Is there some trick or workaround to get this to work? I'd prefer not to just store a plain string of the error, because I want to be able to test if a received error is a certain package-defined error.

    package main

    import (
        "github.com/ugorji/go/codec"
        "errors"
        "fmt"
    )

    var MyError = errors.New("my error")

    type Bar struct {
        Baz string
        Err error
    }

    func main() {
        bar := &Bar{Baz: "my content", Err: MyError}

        // encode
        ch := new(codec.BincHandle)
        var encoded []byte
        enc := codec.NewEncoderBytes(&encoded, ch)
        err := enc.Encode(bar)
        if err != nil {
            return
        }

        // decode
        decbar := &Bar{}
        dec := codec.NewDecoderBytes(encoded, ch)
        err = dec.Decode(decbar)
        if err != nil {
            fmt.Printf("decode attempt 1 failed: %v\n", err)
        }

        decbar = &Bar{Err: errors.New("")}
        dec = codec.NewDecoderBytes(encoded, ch)
        err = dec.Decode(decbar)
        if err != nil {
            fmt.Printf("decode attempt 2 failed: %v\n", err)
        } else {
            fmt.Printf("decode of error gave: %v\n", decbar.Err)
        }
    }

The above code gives:

> decode attempt 1 failed: [pos 25]: cannot decode non-nil codec value into nil error (1 methods)
> decode of error gave:

ie. either the decode fails completely, or I lose my error.

**Comment by ugorji** [comment]
error is an interface. There's a concrete implementation.

However, you cannot take any arbitrary concrete implementation and decode it into an interface, except that implementation already honors that interface.

With no other knowledge, a string is decoded as a string. string does not implement the error interface. So you cannot decode a string into an interface.
