### ISSUE TITLE
Shadowed fields in embedded types are not being encoded

### ISSUE THREAD

**Issue by johnniedoe** [ugorji/go#159]
When encoding structs w/embedded structs, shadowed fields aren't getting encoded.
Unfortunately, this occurs even when the fields' encoded names are changed via struct tags.
```
import (
        "bytes"
        "encoding/json"
        "fmt"

        "github.com/ugorji/go/codec"
)

type Composite struct {
        X string
        Embedded
}

type Embedded struct {
        X string `json:"x"`
}

func main() {
        d := Composite{X:"a",Embedded:Embedded{X:"b"}}
        msg, _ := json.Marshal(d)
        fmt.Println(" json: ", string(msg))

        buf := &bytes.Buffer{}
        codec.NewEncoder(buf, &codec.JsonHandle{}).Encode(d)
        fmt.Println("codec: ", buf.String())
}
```

In this case, the stdlib encoder encodes both values but the codec encoder only encodes the non-embedded value of the Composite struct.

```
 json:  {"X":"a","x":"b"}
codec:  {"X":"a"}
```

Not sure if this is a bug, or just a difference between encoders.

**Comment by ugorji** [comment]
Difference between encoders.

At the edges, these sort of differences are not surprising.

**Comment by johnniedoe** [comment]
Fair enough.

While I was looking into this, I did find another interesting case.
With the same program, if you instead have the structs
```
type Composite struct {
	X string
	Embedded
}

type Embedded struct {
	Y string `json:"X"`
}
```
The stdlib version will not encode the embedded value, while codec will produce an encoded value with two "X" fields.
```
 json:  {"X":"a"}
codec:  {"X":"a","X":"b"}
```
In this case, it's unclear what the receiver of such a payload might do with it.
Granted, it's also a problem that can usually be avoided w/more judicious use of struct tags.

**Comment by ugorji** [comment]
This is a bug!
