### ISSUE TITLE
Allow omitting empty structs when encoding

### ISSUE THREAD

**Issue by 2opremio** [ugorji/go#163]
Probably due to conformance with the golang JSON encoder, empty structs are not omitted when encoding, leading to the same _problem_ outlined in http://stackoverflow.com/questions/18088294/how-to-not-marshal-an-empty-struct-into-json-with-go

We encode data-structures with lots of empty fields (see https://github.com/weaveworks/scope/issues/1201#issuecomment-235205270 ) and it would be desirable to omit serializing them without resorting to pointers or a major rewrite to introduce specialized structure variants.

Maybe a new `omitemptystruct` tag could be introduced?

```go
type Result struct {
    Data       MyStruct  `json:"data,omitemptystruct"`
    Status     string    `json:"status,omitempty"`
    Reason     string    `json:"reason,omitempty"`
}
```

**Comment by 2opremio** [comment]
Oh, I've seen there's an option to enable it in [`helper.go`](https://github.com/ugorji/go/blob/b94837a2404ab90efe9289e77a70694c355739cb/codec/helper.go#L140-L142) but that it may get very expensive since [it checks recursively](https://github.com/ugorji/go/blob/b94837a2404ab90efe9289e77a70694c355739cb/codec/helper_internal.go#L55-L68)

**Comment by ugorji** [comment]
Yeah - it would have been really nice to have a performant IsZero method on reflect.Value for example. See https://github.com/golang/go/issues/7501 . 

However, this may not solve the problem completely (which is why there's still discussion on value of that change).

I will instead put a flag in the Encoder (along with Canonical, etc) so that a user can explicitly request that option.

**Comment by bboreham** [comment]
I cannot see how this applies to the code-generated encoder.  Am I missing something?

**Comment by ugorji** [comment]
@bboreham can you please file a new issue if this doesn't work in codecgen, with a reproducer (main.go with expected output vs received, OR bug_test.go) so I can easily reproduce and fix
