### ISSUE TITLE
codecgen fails on source that is vendored.

### ISSUE THREAD

**Issue by superfell** [ugorji/go#164]
I'm trying to run codecgen for some code that is in a vendor directory, e.g. given
`/src/vendor/bob/bob.go` running `codecgen -o codec.go bob.go`  gives

codecgen error: error running 'go run codecgen-main-9718.generated.go': exit status 1, console: package main
	imports vendor/bob: must be imported as bob

The generate main has
//+build ignore

package main
import "vendor/bob"
func main() {
	bob.CodecGenTempWrite9018()
}

**Comment by superfell** [comment]
This was with go 1.6

**Comment by superfell** [comment]
based on the comments at https://golang.org/src/go/build/build.go?s=9906:9926#L319 seems like the returned ImportPath from ImportDir will have vendor in it in this case.

**Comment by ugorji** [comment]
I will need a reproducer that I can use to reproduce. E.g. provide a main.go that I can run with "go run main.go", and tell me what you expect and what you get.

**Comment by superfell** [comment]
I create an example project that demonstrates this at https://github.com/superfell/codec-issue-164

**Comment by superfell** [comment]
I thought i could work around it by having the build pretend the vendor tree was GOATH, but the vendor tree doesn't start with src, so that's not possible.
