### ISSUE TITLE
support for a tag for json type as encoding/json

### ISSUE THREAD

**Issue by chenjie4255** [ugorji/go#166]
look at golang's example code  which use pakcage encoding/json:

```
package main

import (
	"bytes"
	"encoding/json"
	"log"
	"os"
)

func main() {
	type Road struct {
		Name   string
		Number int `json:",string"`
	}
	roads := []Road{
		{"Diamond Fork", 29},
		{"Sheep Creek", 51},
	}

	b, err := json.Marshal(roads)
	if err != nil {
		log.Fatal(err)
	}

	var out bytes.Buffer
	json.Indent(&out, b, "=", "\t")
	out.WriteTo(os.Stdout)
}
```

there are a tag ```json:",string"``` which help you make make a  convertion from int to a json string, can this pakcage support the same tag?

I thinks it's very useful.

**Comment by ugorji** [comment]
This will not be supported.

This is a feature added to the encoding/json package, which is not applied to any other one.

Instead, we provide the "IntegerAsString" option to the json codec, which solves this much more elegantly.

https://godoc.org/github.com/ugorji/go/codec#JsonHandle
