### ISSUE TITLE
msgpack decoder fails with valid msgpack

### ISSUE THREAD

**Issue by enkore** [ugorji/go#167]
2016/08/19 12:03:01 [pos 11]: readContainerLen: Unrecognized descriptor byte: hex: 13, decimal: 19

File:

```
00000000  83 a7 63 6f 6d 70 61 63  74 81 13 cc a4 a8 73 65  |..compact.....se|
00000010  67 6d 65 6e 74 73 81 13  01 a7 76 65 72 73 69 6f  |gments....versio|
00000020  6e 02                                             |n.|
```

Manual decoding:

0x83 = fixmap with three entries
0xa7 = 7 byte fixstr (compact)
0x81 = fixmap with one entry
**0x13 (offset 10 / byte no 11) = pos fixint,** value = 19, this is the map entry key
0xcc = uint8
0xa4 = value = 164, map entry value

and so on

This works with python-msgpack and probably others.

Issue noticed with msgpack-cli.

**Comment by ugorji** [comment]
You will need to provide a reproducer, that I can run. It should be a main.go file that I can run with "go run main.go" or a xyz_test.go file that I can run with "go test".

Right now, I can't verify and reproduce, and point to how to fix, etc.

**Comment by enkore** [comment]
I don't speak go myself, so the best I can do would be this binary file triggering the issue:

[167.bin.zip](https://github.com/ugorji/go/files/430828/167.bin.zip)

What msgpack-python does with it:

```py
>>> import msgpack
>>> msgpack.load(open('167.bin', 'rb'))
{b'version': 2, b'segments': {19: 1}, b'compact': {19: 164}}
```

And what msgpack-cli based on this library does with it:

```console
$ msgpack-cli decode 167.bin
2016/08/22 20:04:58 [pos 11]: readContainerLen: Unrecognized descriptor byte: hex: 13, decimal: 19
zsh: exit 1     msgpack-cli decode 167.bin
```

**Comment by ugorji** [comment]
I don't even know what msgpack-cli is. 

Seems like they are the ones that you should contact with a bug report. Maybe they are not using the msgpack library correctly???

**Comment by enkore** [comment]
https://github.com/jakm/msgpack-cli

**Comment by ugorji** [comment]
I will close this bug report now.

This is a bug report for msgpack-cli, not for the library underneath.

If msgpack-cli thinks it is a msgpack library issue, then they can file a report and a representative bug description. Or you can file it directly for this library if you can demonstrate that the problem is with this library, and not with the layer above. For example, msgpack-cli may not have the appropriate options set, etc.

**Comment by enkore** [comment]
Works for me
