### ISSUE TITLE
Delayed/partial decoder

### ISSUE THREAD

**Issue by vovanec** [ugorji/go#169]
It's rather question or/and feature request. Can I partially decode JSON/msgpack keeping some inner parts as []byte for later? I can easily do this with builtin json, here's the example: https://play.golang.org/p/1C-V98MODB

From documentation:
// RawMessage is a raw encoded JSON value.
// It implements Marshaler and Unmarshaler and can
// be used to delay JSON decoding or precompute a JSON encoding.
type RawMessage []byte

Thanks,
--Vovan

**Comment by ugorji** [comment]
This library cannot do this at the moment. 

Add this as a feature request.
