### ISSUE TITLE
Using SetBytesExt together with CodecSelfEncode / CodecSelfDecode

### ISSUE THREAD

**Issue by tobiemh** [ugorji/go#173]
Currently I am using the `SetBytesExt` method on the handle to add a custom extension to BINC/MsgPack using `ReadExt` and `WriteExt`.

However, for more advanced types, it would be better to be able to generate the self encoding and decoding methods using the codec generator. At the moment if a type is registered as a custom extension using `SetBytesExt`, then the `CodecSelfEncode` and `CodecSelfDecode` methods are not used.

I was wondering whether it is already possible (or perhaps is planned) to assign a type to a custom extension, whilst at the same time using the codec generator to generate the implementations for `CodecSelfEncode` and `CodecSelfDecode`?

---

Although not a direct comparison the [msgp](https://github.com/tinylib/msgp) library allows you to use the `ExtensionType` method to specify the extension int, and then use `MarshalBinaryTo` and `UnmarshalBinary` to encode and decode.

**Comment by ugorji** [comment]
Those are 2 parallel ways of configuring how it is encoded. You can only do one. So we check a bunch in sequence (with SetBytesExt taking precedence).

However, you can achieve what you want. Within your SetBytesExt callback, call the CodecSelf(En|De)code methods.
