### ISSUE TITLE
Encoding floats in JSON uses decimal exponents for all values small or large

### ISSUE THREAD

**Issue by tobiemh** [ugorji/go#174]
When encoding floats in JSON the scientific notation is used even for small exponents. So for example encoding `0.1` will return `1E-01` and `1.0` will return `1E+00`.

The current 2 lines of code which affect this output are [json.go#L200](https://github.com/ugorji/go/blob/master/codec/json.go#L200) and [json.go#L205](https://github.com/ugorji/go/blob/master/codec/json.go#L205). On these lines the AppendFloat method is using the `'E'` format.

Is this intentional behaviour? ...or would it be better to use `'G'` (which according to [strconv](https://golang.org/pkg/strconv/#FormatFloat) will use `'E'` for large exponents, and `'f'` for small exponents). If this is actually intentional, would it be possible to add this as an optional flag?

---

Example:
```go
package main

import (
	"fmt"
	"github.com/ugorji/go/codec"
)

func main() {

	var h codec.JsonHandle
	var d interface{}
	var i, o []byte

	i = []byte(`{"test":1.0}`)

	codec.NewDecoderBytes(i, &h).Decode(&d)
	codec.NewEncoderBytes(&o, &h).Encode(&d)

	fmt.Printf("Initial: %s\nEncoded: %s", i, o)

}
```

Output:
```
Initial: {"test":1.0}
Encoded: {"test":1E+00}
```

**Comment by ugorji** [comment]
Good catch.

For precision (as this package tries to infer whether a float or an int), we have to always have an E or a . in the number when encoding.

Fix coming.
