### ISSUE TITLE
Performance question MsgPack: Map vs Struct

### ISSUE THREAD

**Issue by thienohs** [ugorji/go#176]
Hi, I had a simple performance technical question (not sure where I can ask this so pardon me if this is not the right place, I think it would be useful information for other developers as well):

If i had a piece of data like below, just imagine you got a billion of these messages to process,
Sometime it could be:
{
1:'To do 1'
2:255
}
Sometime it could have the extra third parameter:
{
1:'To do 2'
2:255
3:true
}

The question is with current implementation of MsgPack, Would parsing to a pre-defined Struct faster or slower than parsing to an arbitrary map in Go (ex: map[byte]interface{}) ?

**Comment by ugorji** [comment]
Structure is faster. You can always test it out and benchmark it.

**Comment by thienohs** [comment]
Thank you. 
I confirmed. Use struct half the parsing time in all tests.
