### ISSUE TITLE
Go vet warnings

### ISSUE THREAD

**Issue by mrz1836** [ugorji/go#183]
`vendor/github.com/ugorji/go/codec/gen-helper.generated.go:1: possible malformed +build comment
vendor/github.com/ugorji/go/codec/simple.go:343: unrecognized printf verb ' '
exit status 1`

**Comment by ugorji** [comment]
The first one is not a bug, and cannot be solved, as we want a way to comment this out. I think the vet tool should be changed to not flag this.

The second one is a bug, and I have now fixed (but not uploaded upstream yet)

**Comment by ugorji** [comment]
K - I can change it to /*  */ to prevent "vet" from flagging as a potential issue.

Fix coming soon.

**Comment by ugorji** [comment]
Fixed with 2 changes above
