### ISSUE TITLE
DoS when decoding corrupt string or bytes data

### ISSUE THREAD

**Issue by arodland** [ugorji/go#187]
When `decByteSlice` is called with a nil or too-short `[]byte`, it will try to allocate a new `[]byte` with size `clen`, which is the container length provided by the decode driver. If we try to decode a corrupted message that claims to contain a very large string or bytes value (even if it doesn't), this can either crash the program with an out-of-memory error, or cause very bad performance. This could be the result of random data corruption, or malicious intent. It only takes six or so bytes of msgpack data to make codec allocate up to 4GB. This is dangerous when decoding any kind of input that comes from the outside world.

Some possible ways to mitigate:

1. Provide a decoder option giving a maximum string size. On encountering a string or bytes value over that size, throw an error.
2. In cases where the size of the input is known, error on being told to expect a string or bytes value that's larger than the entire remaining data. (not feasible with the current Reader interface)
3. Only pre-allocate up to a certain, safe size; for larger sizes fall back to a loop that reads by chunks and appends them to the output buffer. This accomplishes something similar to option 2, but without having to know the size of the input in advance.

Option 1 is the easiest; option 1 + option 3 would be my ideal solution.

**Comment by ugorji** [comment]
Thanks.

A Decoder Option for this already exists, but it was only used for slices (except []byte), map and chan. It will now be expanded to support strings/byte slices.

Fix coming soon.

**Comment by ugorji** [comment]
Use Handle Option MaxInitLen, after applying this fix.
