### ISSUE TITLE
Interface-type extensions

### ISSUE THREAD

**Issue by romshark** [ugorji/go#188]
I currently came across a design flaw defining an extension for multiple types implementing a shared interface. I've got an interface type "Identifier":

```
type Identifier interface {
	FromBytes([]byte) error
	FromString(string) error
	Bytes() []byte
	String() string
}
```

This interface is implemented by "UserId", "FileId", "CollectionId" and "ObjectId" and to me it seems like defining an extension for each of those types breaks the DRY principle, it makes more sense to actually define an extension for the interface rather the types, but when I tried to provide the interface as type it failed telling me: "codec.Handle.AddExt: Takes named type, not a pointer or interface: <nil>"

My question is whether it could make sense to define interface-type extensions and whether it's possible technically speaking?

**Comment by ugorji** [comment]
Unfortunately, it cannot work that way.

First, you cannot get a reflect.Type for an interface. An interface is just a holder object that contains a Type and a value. So what you are asking for is not possible.

Secondly, the design requires that a type may have an associated id, that is logged in the stream, and is used to figure out what "type" to decode into. An interface is not specific enough e.g. everything is an interface{}, but all different types.

You should use SetBytesExt or SetInterfaceExt explicitly for each type.
