### ISSUE TITLE
Disable the escaping of <, >, and & in JSON strings.

### ISSUE THREAD

**Issue by dadgar** [ugorji/go#189]
It would be great to get the same option as Go's build in JSON encoder. 

https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML
https://github.com/golang/go/commit/ab52ad894f453a02153fb2bc106d08c47ba643b6

**Comment by ugorji** [comment]
How soon do you need this fixed?

**Comment by dadgar** [comment]
We are doing a release of Nomad within a week and the next one will likely be a month after that. Obviously would prefer getting it fixed for this release but given the tight timing makes total sense if it doesn't make it!

**Comment by ugorji** [comment]
K. Will release fix by tomorrow.

**Comment by ugorji** [comment]
You're welcome. Let me know how it works. Use the option: HTMLCharsAsIs=true .

**Comment by dadgar** [comment]
@ugorji It worked well! Thanks again!
