### ISSUE TITLE
Verification fails if ImportPath contains vendor keyword

### ISSUE THREAD

**Issue by armstrongli** [ugorji/go#192]
Verification fails with error message : 

> example.com/vendor/example2.com/test must be import as example2.com/test

The generated code includes the import path `import "example.com/vendor/example2.com/test"`, and fails.

It happens when the code being generated is in vendor path.

**Comment by ugorji** [comment]
I need a small reproducer, so I can validate the error you are receiving.

Please attach steps to reproduce the error, and I will look into it. Right now, it seems like the code is correct.

**Comment by ugorji** [comment]
@armstromgli ^^ I need a reproducer, or I will close this and you can re-open it with a reproducer.

**Comment by ugorji** [comment]
@armstrongli ^^ I need a reproducer, or I will close this and you can re-open it with a reproducer.
