### ISSUE TITLE
Zero-copy not working because Decoder.bytes is never set

### ISSUE THREAD

**Issue by bboreham** [ugorji/go#193]
It is read in various decoders, e.g. at https://github.com/ugorji/go/blob/master/codec/msgpack.go#L730, but there is no code where `bytes` is set.

This has the effect that most of the zero-copy code in msgpack.go is never called.

**Comment by bboreham** [comment]
That fix is not effective because it is called after the value of `bytes` is read.

**Comment by ugorji** [comment]
Sorry - incomplete fix. Please try now.

**Comment by bboreham** [comment]
Yes, that works, thanks.
