### ISSUE TITLE
lint failures in generated type files

### ISSUE THREAD

**Issue by spzala** [ugorji/go#194]
The ugorji go library is used by kubernetes and other related projects.
The changes in this patch takes care of lint failure several, total 90,
lint failures. The main types of failure includes,
    - Superfluous or irrelevant usage of bool variables
    - Generated functions name have underscore in them
    - error var is not in a recommended format
    - Exported functions are missing doc comments
    - Const variables name are using underscore in them

For example, some of the common failure/error messages are:
    - should omit type bool from declaration of var ; it will be inferred from the right-hand side
    - don't use underscores in Go names; method should be
    - exported method should have comment or be unexported
    - don't use underscores in Go names; const should be
    - error var should have name of the form errFoo

**Comment by ugorji** [comment]
Linting cannot be done now. It makes major changes to generated code. We may look into it later.

**Comment by ugorji** [comment]
Closing this as we will not make changes to the code-generator. 

The code-generator will pass "go vet", but not "go lint". Pursuing a goal of passing "go lint" will make wholesome changes to generated code, which users do not like.
