### ISSUE TITLE
Adding new struct tags for specific codecs.

### ISSUE THREAD

**Issue by szank** [ugorji/go#197]
Hi, I have a question regarding the struct tags used by the codec. 
As far as I understood from the http://ugorji.net/blog/go-codec-primer (section `Source configuration (for encoding)`), there are two recognized struct tags. 
`codec` and `json`. `Codec` takes precedence. I was wondering if it was possible to add struct tags for each protocol. 
For example:
```
type RequestStruct struct{
    InternalField string `json:"-"           cbor:"internalfield"`
    RequestField  string `json:"requestfield" cbor:"requestfield"`
}
```
In our case, we retrieve JSON requests in our RESTful API, and we wanted to add some new, internal information to the decoded struct, encoded it in cbor for example (to save some bandwidth) and pass it along for further processing. 
Now, we obviously wouldn't advertise in our API the InternalField field(which as the name suggest is not public), and even if the name have been brute-forced by a malicious client, codec gives us an option to return an decoding error on unrecognized field. So far so good. The problem arises if we set the `InternalField` ourselves and want to reencode the struct. 
The only option available for us at the moment, is to create two structures: 

```
type RequestStruct struct{
    RequestField  string `codec:"requestfield"`
}

type internalRequestStruct struct{
    RequestStruct
    InternalField string `codec:"internalfield"`
}
```

Which means more potentially avoidable allocations. It is not super bad, but we are using codec package to avoid unnecessary copies ;)

As far as deciding which struct tag to use to encode/decode fields, the precedence would be : 
```
1. The "msgpack","cbor","json" tag
2. The "codec" tag
3. Canonical name of the field
```

Second concern: 
As far as I understand, one can use the `json` struct tags to define how cbor, binc and msgpack messages should be decoded/encoded wich is a bit misleading. 

What would be even better is to allow users do define different behaviour on encoding and decoding, for example : 

```
type RequestStruct struct{
    InternalField string `codec:"dec=-,enc=internalfield"`
    RequestField  string `codec:"requestfield"`
}
```
Where `dec` and `enc` specify decoding and encoding behaviour

The only issue with backward compatibility of my proposal is the situation where users of the library use `json` tags to direct the encoding of msgpack/cbor/binc payloads.

**Comment by ugorji** [comment]
These 2 concerns can be broken down, or solved via the library.

Every handle has a field called TypeInfos, which can be initialized using the NewTypeInfos([]string) function, that takes a set of tag names. By default, if not specified, we will use the default TypeInfos, which is configured to use codec and json (json was added for compatibility with encoding/json, as they mostly use similar tags).
