### ISSUE TITLE
Document that omitempty is ignored with toarray

### ISSUE THREAD

**Issue by akalin-keybase** [ugorji/go#198]
e.g. with

```
       type t1 struct {
               _struct bool `codec:",toarray"`
               B1 bool
               B2 bool `codec:",omitempty"`
       }
```

`B2` will always be encoded.

This isn't explicitly mentioned anywhere, and an example in http://ugorji.net/blog/go-codec-primer (`type My2`) incorrectly suggests it's possible. Or maybe it's planned to be? It would seem to be complicated/ambiguous in the general case, though.

**Comment by ugorji** [comment]
Thanks. 

Toarray means everything must be encoded, as we map the position to the array to the position of the field in the struct.

Will update comments and doc and then close.

**Comment by ugorji** [comment]
Also updated doc at  http://ugorji.net/blog/go-codec-primer
