### ISSUE TITLE
Broken etcd and registrator

### ISSUE THREAD

**Issue by juliangamble** [ugorji/go#205]
Hi @ugorji, 

This latest release has broken lots of upstream libraries. Could you please publish a branch with the old version so we can keen building against the old version?

Cheers
Julian

**Comment by ugorji** [comment]
Did your re-run codecgen?

**Comment by ugorji** [comment]
@juliangamble ^^

**Comment by ugorji** [comment]
Closing due to no-response. Please respond and ping me so I can re-follow up if this is still an issue.

**Comment by steve-gray** [comment]
@ugorji - It's not that people haven't re-run codecgen, it's that the API changes are breaking pre-existing libraries that people are 'go getting' - i.e. When I depend on other peoples code. Vendoring is not inherited.

If you could take the state @ bdcc60b419d136a85cdf2e7cbcac34b3f1cd6e57 for example, and then tag that - it'd let people easily configure go dep to work around the issue, as it seems to struggle with pinning a specific hash for this package.

````
[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.0.0"
````

That the API changes are breaking is still a PITA for folks, but at least it's readily mitigated. Versioning akin to how MGO approaches it would be ideal, but that's a dramatic change that would require more work on your part.

**Comment by ugorji** [comment]
Is this still a problem?

I will be releasing a v1.1 in the next few days, but I also tried hard to maintain the API surface area for codecgen, so that a re-run is not strictly required.

**Comment by ugorji** [comment]
^^ @steve-gray

**Comment by ugorji** [comment]
FYI @steve-gray @juliangamble v1.1 is now released. See https://github.com/ugorji/go/releases/tag/v1.1
