### ISSUE TITLE
Would like to be able to disable extension support in codecgen-generated code

### ISSUE THREAD

**Issue by bboreham** [ugorji/go#207]
We don't use the extensions feature, so having it in the code has a couple of downsides:
 - it causes the receiver of `CodecDecodeSelf()` to escape, so the Go compiler will always move it to the heap; in certain circumstances this creates a lot of garbage
 - it causes a little extra work to check if there are any handlers for every element.

Therefore I would like an option on `codecgen` to disable extensions and stop generating this line:

    } else if z.HasExtensions() && z.EncExt(x) { 

Happy to do a PR myself.

**Comment by ugorji** [comment]
I have a few changes in process to codec.

Let me think this through.

**Comment by ugorji** [comment]
Fixed via 50530d8d1478c8bbfbdb18cbf5465db9aee6ada4
