### ISSUE TITLE
"no buildable go sources files in $PATH"

### ISSUE THREAD

**Issue by richardartoul** [ugorji/go#211]
Example:

```bash
go run ./vendor/github.com/ugorji/go/codec/codecgen/gen.go -c "github.com/ugorji/go/codec" -o out.go "github.com/ugorji/go/codec" tools/verify_commitlogs/main/main.go 
codecgen error: no buildable Go source files in /Users/richardartoul/gocode/src/github.com/m3db/m3db
```

This seems to happen regardless of whether I use a relative path or a fully qualified path

**Comment by ugorji** [comment]
This is not a bug. You are not running this in the way it was designed.

You are trying to run an executable within go run. 

You should create the executable, and then run it.
