### ISSUE TITLE
how can I unmarshal json with string-key?

### ISSUE THREAD

**Issue by Lwxiang** [ugorji/go#217]
```
type Storage struct {
   Data interface{} `json:"data"`
}
```
I have a struct ```Storage``` and use it to decode a json which is like:
```
{
   "data": {
         "hello": "world",
         "foo": "bar"
   }
}
```
but after decoding, the "hello" and "foo" will be type interface{}, how can i unmarshal the json to make the key type string?

**Comment by ugorji** [comment]
Paste code snippet, and then I can help you.

**Comment by ugorji** [comment]
You have to provide:
- reproducer (a main.go or main_test.go): that I can run with "go run main.go" or "go test"
- what you expect to see on the standard output
- what you get instead on the standard output

**Comment by Lwxiang** [comment]
```go
type GD struct {
    Data interface{} `json:"a"`
}

func main() {
    var jsn = codec.JsonHandle{}
    r := []byte("{\"a\":{\"b\":1}}")
    dec := codec.NewDecoderBytes(r, &jsn)
    var s GD
    var s2 GD
    if err := dec.Decode(&s); err != nil {
        fmt.Println(err.Error())
    } else {
        fmt.Printf("%+#v\n", s)
    }

    if err := json.Unmarshal(r, &s2); err != nil {
        fmt.Println(err.Error())
    } else {
        fmt.Printf("%+#v\n", s2)
    }
}
```

output:
```
main.GD{Data:map[interface {}]interface {}{"b":0x1}}               // codec
main.GD{Data:map[string]interface {}{"b":1}}                          // golang std
```
Can I unmarshal the json like what golang std package do? 
All I want is "key is string"

**Comment by ugorji** [comment]
Add a line: jsn.MapType = reflect.TypeOf(map[string]interface{}(nil))

This should now work.

**Comment by ugorji** [comment]
See https://godoc.org/github.com/ugorji/go/codec#DecodeOptions

**Comment by Lwxiang** [comment]
That works. Thank you for your help!
