### ISSUE TITLE
Update docs or add default implementation for MapBySlice()

### ISSUE THREAD

**Issue by Niondir** [ugorji/go#219]
Since I stumbled upon it I like to suggest to provide an example how to implement MapBySlice:

```
type MapBySliceType []interface{}

func (_ MapBySliceType) MapBySlice() {

}
```

Or providing the above implementation as some kind of default that can be used.

Especially a note on the fact that it does not work when you implement the `MapBySlice()` function with a pointer receiver.

Or should the lib be fixed, that pointer receivers also work?

P.S. it's a great feature! :)

**Comment by ugorji** [comment]
I will expand the docs on MapBySlice to include a sample snippet. And make clear that the type MUST be a slice type, and specifically the slice type, that implements MapBySlice.
