### ISSUE TITLE
CodecDecodeSelf is not if initial bytes are represent nil in the format

### ISSUE THREAD

**Issue by Jack47** [ugorji/go#230]
This is the demo code to demonstrate that `RespStat` implements codec.Selfer but `CodecDecodeSelf` is not called when decoding `RespStat`, so the decoded result is not expected. I find the root cause is [TryDecodeAsNil](https://github.com/ugorji/go/blob/master/codec/decode.go#L2019) branch succeed and bypassed the other branch. because I encoded the first field r.Err, and in the below example, it is nil map, so the encoded bytes are "c0...". so the final decoded result is a struct will fields set to nil. 
```
package main

import (
	"bytes"
	"fmt"
	"reflect"

	"github.com/ugorji/go/codec"
)

// Pack Header: statMessage | statRelayMessage
type ClusterError struct {
	ErrorCode int
}

type RespStatPayload interface {
	Aggregate(bool, map[string]RespStatPayload) (RespStatPayload, error)
}

type RespStat struct {
	Err     error
	Payload RespStatPayload
}

// many concrete struct types which implements RespStatPayload
type ResultStatIndicatorValue struct {
	MemberName string      `json:"-"` // omit it when writing http json result
	Name       string      `json:"name,omitempty"`
	Value      interface{} `json:"value"`
}

func (r ResultStatIndicatorValue) Aggregate(detail bool, otherIndicatorValue map[string]RespStatPayload) (RespStatPayload, error) {
	return nil, nil
}

// RespStat imlement codec.Selfer interfacer, which decode or encode itself
// These two functions are used by codec.Decoder, codec.Encoder
func (r *RespStat) CodecDecodeSelf(dec *codec.Decoder) {
	dec.MustDecode(&r.Err)
	var typ int8
	dec.MustDecode(&typ)

	var payload RespStatPayload
	switch typ {
	case 1:
		payload = &ResultStatIndicatorValue{}
	default:
		panic(fmt.Sprintf("unimplemented StatType: %v", typ))
	}
	dec.MustDecode(&payload)
	r.Payload = payload
}

func (r *RespStat) CodecEncodeSelf(enc *codec.Encoder) {
	enc.MustEncode(&r.Err)
	var typ int8
	switch v := r.Payload.(type) {
	case *ResultStatIndicatorValue:
		typ = 1
	default:
		panic(fmt.Sprintf("unimplemented Stat: %v", reflect.TypeOf(v)))
	}

	enc.MustEncode(&typ)
	enc.MustEncode(&r.Payload)
}

func main() {
	h := codec.MsgpackHandle{}

	bb := RespStat{
		Payload: &ResultStatIndicatorValue{
			Name:  "COUNT_1",
			Value: 1.0,
		},
	}
	buff := bytes.NewBuffer(nil)

	encoder := codec.NewEncoder(buff, &h) //
	err := encoder.Encode(&bb)            //
	if err != nil {                       //
		fmt.Printf("encode failed: %v", err) //
	} //

	//var bbb BB
	bbb := &RespStat{}
	decoder := codec.NewDecoder(bytes.NewReader(buff.Bytes()), &h)

	fmt.Printf("%x\n", buff.Bytes())
	err = decoder.Decode(bbb)
	if err != nil {
		fmt.Printf("decode failed: %v", err)
	}
	fmt.Printf("decoded %+v\n", bbb)

}
```
Currently I can solve this problem temporarily by encode/decode other non-map fields first. But I think we need to improve the line decode.go#L2019 to add more conditions to avoid the above situations.
Hope this makes sense, thanks!

**Comment by ugorji** [comment]
I think you should change your code to encode a value (tag, etc) that represents the structure first, so that the first but did not estate to a nil. 

I can document this better, so folks are aware. But this is only happening because of how you implemented CodecEncodeSelf, along the first bytes to represent nil.

**Comment by Jack47** [comment]
Em, documentation is good, but users rarely read them carefully, I think it would be better to not impose this  limitation on CodecEncodeSelf. Any way I respect your decision.

**Comment by ugorji** [comment]
We can't not impose the limitation. We always check first if a nil was encoded, and we never read more than the minimum number of bytes from the stream. This idea is a unique corner case, that will not work the first time you try it, making you read doc and see the limitation. And most folks implementing CodecSelfer will use codecgen, or register an extension for customers types. In short, this is a very rare idea which you did, and we shouldn't blow up a long-held design for a rare use case, when clear docs suffice. Engineering is all about tradeoffs, and this is the right trade-off.

**Comment by Jack47** [comment]
Sounds reasonable, thanks for explaination, it really helps!
By the way, I  first registered an extension for customer types {because there are good examples in the doc} , but finally I choose to use codec.Selfer interface, because it's more straight forward just like implement json.Marsha/Unmarshal, don't need to register on handler. will have a look on codecgen.
