### ISSUE TITLE
time.Time values encoding using MessagePack handles

### ISSUE THREAD

**Issue by partomatl** [ugorji/go#234]
I think there might be a problem with the way `time.Time` values are encoded by MessagePack handles.

```go
type Object struct {
	Date time.Time `codec:"date"`
}
```

Everything works fine when I encode an `Object` value and then decode it using a pointer to an `Object`.
```go
// creating an Object
date := time.Date(2017, 01, 01, 0, 0, 0, 0, time.UTC)
obj := Object{Date: date}

// encoding obj in b
var b []byte
var h codec.Handle = new(codec.MsgpackHandle)
var enc = codec.NewEncoderBytes(&b, h)
var err = enc.Encode(obj)
if err != nil {
        panic(err)
}

// take a look at the encoding ([]byte and hex)
log.Print(b) // [129 164 100 97 116 101 164 88 104 70 128]
log.Printf("%x", b) // 81 A4 64 61 74 65 A4 58 68 46 80
        
// decoding b into objDecoded
var hd codec.MsgpackHandle
var dec = codec.NewDecoderBytes(b, &hd)
var objDecoded Object	
err = dec.Decode(&objDecoded)
if err != nil {
        panic(err)
}

// the date field is perfectly decoded
log.Printf("%+v", objDecoded) // {Date:2017-01-01 00:00:00 +0000 UTC}
```

However when I decode into an `interface{}`, here is what happens:

```go
// decoding b into interfaceDecoded
var interfaceDecoded interface{}
err = dec.Decode(&interfaceDecoded)
if err != nil {
        panic(err)
}

// the date field is not properly decoded
log.Print(interfaceDecoded) // map[date:[88 104 70 128]]
// when setting hd.RawToString = true, it prints map[date:XhF�]

```

I think this is happening because as seen above, the date field is encoded (in hex) as such:
> 81 A4 64 61 74 65 **_A4_ 58 68 46 80**

While `58 68 46 80` is the correct encoding of the `time.Time` value (timestamp `1483228800`), it is preceded by the `A4` marker which indicates a `fixstr` of length 4.
According to the [MessagePack specification](https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type), the marker preceding the timestamp should be `D6`, `D7` or `C7`.

The same thing happens when using `codecgen`.

What do you think?

**Comment by partomatl** [comment]
My bad, looking at the [EncodeTime()](https://github.com/ugorji/go/blob/master/codec/msgpack.go#L303) method I saw that you have to configure `h.WriteExt = true` to be compatible with the updated MessagePack spec. And it's even written [in the doc](http://ugorji.net/blog/go-codec-primer#messagepack).

Sorry!

**Comment by ugorji** [comment]
@partomatl sounds good. Closing.
