### ISSUE TITLE
Parsing chunked, partially broken data

### ISSUE THREAD

**Issue by Albibek** [ugorji/go#235]
Hello.

I'm trying to parse some byte data(my case is JSON, but it dosn' matter) in chunks. Chunks, depending on their size an contain any number of full messages. I also assume that some bad(i.e. unparseable) data may exist between good records. 

The good case I see here is having a buffer and use DecoderBytes on it, but there is some information from Decoder that is missing - the position in buffer where last message have been parsed with success. This case would allow to cut the good message from buffer and then do some additional logic on buffer to deal with bad/incomplete data(fill buffer, delete bad data, etc), calling ResetBytes on decoder afterwards. 
Is this possible to retrieve such information somehow? How hard would it be to patch the module to do somethig like that?

**Comment by stdupp** [comment]
when this feature release ?
