### ISSUE TITLE
Consider using strings Builder to improve encoding/decoding performance

### ISSUE THREAD

**Issue by 2opremio** [ugorji/go#238]
I may be wrong, but I think there are parts of the marshalling/unmarshalling code which could benefit from Go 1.10's [`strings.Builder`](https://golang.org/pkg/strings/#Builder) (or at least use a more streamlined way to gain performance without resorting to `unsafe` tricks directly)

**Comment by ugorji** [comment]
Not clear where I can use strings.Builder. This is because we use bytes and append internally.

If there is a place you see strings.Builder playing a role, please let me know. But I don't see it.
