### ISSUE TITLE
Parsing a JSON stream with nested objects

### ISSUE THREAD

**Issue by StefanFransen** [ugorji/go#242]
Hi,

I need to process a large JSON file (2.3GB).First I tried using the `encoding/json` Decoder function, but this doesn't work without al lot of hacks. So I found this library.

My JSON file contains multiple nested objects. At the moment I'm using the following example.
http://ugorji.net/blog/go-codec-primer#encode-decode-from-to-chan-type-for-iterative-streaming-support

This works okay-ish but the child objects are decoded the same time as the parent objects.
I thought about creating another decoder inside the `go func()` but this would get very messy and ugly quickly.

I can provide a JSON file for more information. But some more information on this would be enough!

Thanks in advance.

**Comment by ugorji** [comment]
I don't understand. Please post a reproducer, with code and associated json file, so I can help.

**Comment by StefanFransen** [comment]
The current code I'm using based on your example.

```
package main

import (
  "net/http"
  "bufio"
  "log"
  "io"

  "github.com/ugorji/go/codec"
)

func main() {
  //no auth required, available for anyone
  resp, err := http.Get("https://daisycon.io/datafeed/?filter_id=40831&settings_id=6267")
  if err != nil {
    log.Panic(err)
  }
  defer resp.Body.Close()

  var r *bufio.Reader

  var h codec.JsonHandle // or CborHandle, or MsgpackHandle, etc
  if _, ok := resp.Body.(io.ByteScanner); !ok {
      r = bufio.NewReader(resp.Body)
  } // use a buffered reader for efficiency
  ch := make(chan interface{}, 128) // channel to decode into
  finish := make(chan struct{}) // unbuffered channel for signaling goroutine finish
  go func() {
      for e := range ch { // process till all values are received and channel is closed
          log.Println(e)
      }
      finish <- struct{}{} // send signal closing channel
  }()
  var dec *codec.Decoder = codec.NewDecoder(r, &h)
  err = dec.Decode(&ch)
  close(ch)
  <- finish // wait for goroutine to finish processing channel
}
```
If you run this code you see the word `datafeed` printed first and then the second object at once.
What I'm trying to do is to loop through each of the child objects instead of just the parent object.

**Comment by ugorji** [comment]
You want to do some thing like this:

```
type Doc struct {
  D Datafeed `codec:"datafeed"`
}

type Datafeed struct {
  I Info `codec:"info"`
  P chan Program `codec:"programs"`
}

type Program struct {
  Pi ProgramInfo `codec:"program_info"`
  Pp []Product   `codec:"products"`
}

type Product struct {
  Ui UpdateInfo `codec:"program_info"`
  Pp map[string]interface{}   `codec:"product_info"`
}

type UpdateInfo struct {
  // ... fill in
}

type ProgramInfo struct {
  // ... fill in
}

```

What this allows, is that the Program values are encoded into a chan (as opposed to a slice), so that they can be consumed from the channel without eating up all the memory.

Now, what you have to do is this:

```
var r io.Reader // reader holding the json contents
var d Doc
d.D.P = make(chan Program)
var finish = make(chan struct{})
go func() {
log.Printf("All Programs from the json file ...\n")
  for e := range d.D.P {
    log.Printf("%v\n", e)
  }
  finish <- struct{}{} // send signal closing channel
}
var h JsonHandle
h.ReaderBufferSize=2048
var dec = codec.NewDecoder(r, &h)
err := dec.Decode(&d)
close(ch)
<- finish // wait for goroutine to finish processing channel
```

**Comment by ugorji** [comment]
Hope this helps. Closing now as this is more a question than an issue. Add comments and tag me ( @ugorji ) if you need more help.
