### ISSUE TITLE
Encoder ignores Marshaller Interface

### ISSUE THREAD

**Issue by agupt** [ugorji/go#245]
Below is test case I am testing. I have created `int` type called `AliasType` which implements Marshaler interface. I expect `codec.Encoder` to use custom marshaler but instead it ignores it and encodes aliastype as integer. Let me know if i am doing something wrong. I am using go1.10.1 and using library at commit `f3cacc17c85ecb7f1b6a9e373ee85d1480919868`

```
type AliasType int

func (a AliasType) MarshalJSON() ([]byte, error) {
	return []byte(`"` + "aliastype" + `"`), nil
}

type TestEncoding struct {
	A AliasType `json:"a"`
}

func Test_AliasTypeEncoding(t *testing.T) {
	exp := "{\"a\":\"aliastype\"}"
	te := TestEncoding{A: 1}
	buf := bytes.Buffer{}
	enc := codec.NewEncoder(&buf,&codec.JsonHandle{})
	err := enc.Encode(te)
	if err != nil {
		t.Error(err)
	}
	data := buf.String()
	if data !=  exp {
		t.Errorf("invalid json encoding using ugroji %s", data)
	}

	bytes, err := json.Marshal(te)
	if err != nil {
		t.Error(err)
	}
	if string(bytes) != exp {
		t.Errorf("invalid json encoding using STL %s", string(bytes))
	}

}
```

**Comment by ugorji** [comment]
Try implementing UnmarshalJSON and see if that helps. If so, I can explain what is happening.

**Comment by ugorji** [comment]
See https://godoc.org/github.com/ugorji/go/codec#hdr-Custom_Encoding_and_Decoding Your type MUST implement MarshalJSON and UnmarshalJSON, for us to treat it as you intend.

**Comment by agupt** [comment]
@ugorji  Maybe this is change is behaviour. Older version of library did not require us to implement both Marshaler and UnMarshaler interface. If you run above example with commit `5cd0f2b3b6cca8e3a0a4101821e41a73cb59bed6` test would pass.  

Any ways your suggestion worked: 
```
type AliasType int

func (a AliasType) MarshalJSON() ([]byte, error) {
	return []byte(`"` + "aliastype" + `"`), nil
}

func (a AliasType) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s) ; err != nil {
		return err
	}
	return nil
}

type TestEncoding struct {
	A AliasType `json:"a"`
}

func Test_AliasTypeEncoding(t *testing.T) {
	exp := "{\"a\":\"aliastype\"}"
	te := TestEncoding{A: 1}
	buf := bytes.Buffer{}
	enc := codec.NewEncoder(&buf,&codec.JsonHandle{})
	err := enc.Encode(te)
	if err != nil {
		t.Error(err)
	}
	data := buf.String()
	if data !=  exp {
		t.Errorf("invalid json encoding using ugroji %s", data)
	}

	bytes, err := json.Marshal(te)
	if err != nil {
		t.Error(err)
	}
	if string(bytes) != exp {
		t.Errorf("invalid json encoding using STL %s", string(bytes))
	}

}
```

**Comment by ugorji** [comment]
@agupt fair enough. That symmetry change (fix) has been in for over a year now though.
