### ISSUE TITLE
omitempty works for structs even with RecursiveEmptyCheck=false

### ISSUE THREAD

**Issue by akalin-keybase** [ugorji/go#250]
Repro test:

```
package main

import (
	"bytes"
	"testing"

	"github.com/ugorji/go/codec"
)

type S struct {
	A int
}

type T struct {
	A S
}

type TOmitempty struct {
	A S `codec:",omitempty"`
}

func TestDecodeOmitEmpty(t *testing.T) {
	t1 := T{}
	t2 := TOmitempty{}

	var mh codec.MsgpackHandle

	var encoded1 []byte
	e1 := codec.NewEncoderBytes(&encoded1, &mh)
	e1.MustEncode(t1)

	var encoded2 []byte
	e2 := codec.NewEncoderBytes(&encoded2, &mh)
	e2.MustEncode(t2)

	if !bytes.Equal(encoded1, encoded2) {
		t.Fatalf("mh=%+v, encoded1=%x != encoded2=%x", mh, encoded1, encoded2)
	}
}
```

prints:

```
go test .
--- FAIL: TestDecodeOmitEmpty (0.00s)
	decode_test.go:37: mh={BasicHandle:{TypeInfos:<nil> extHandle:[] intf2impls:[] RPCOptions:{RPCNoBuffer:false} DecodeOptions:{MapType:<nil> SliceType:<nil> MaxInitLen:0 ReaderBufferSize:0 ErrorIfNoField:false ErrorIfNoArrayExpand:false SignedInteger:false MapValueReset:false SliceElementReset:false InterfaceReset:false InternString:false PreferArrayOverSlice:false DeleteOnNilMapValue:false} EncodeOptions:{WriterBufferSize:0 StructToArray:false Canonical:false CheckCircularRef:false RecursiveEmptyCheck:false Raw:false}} RawToString:false NoFixedNum:false WriteExt:false binaryEncodingType:{} noElemSeparators:{} _:[0]}, encoded1=81a14181a14100 != encoded2=80
FAIL
```
Since `A` is of struct type and `RecursiveEmptyCheck` is false, I expect it to not be omitted even if `omitempty` is set.

git bisect points to d41456c8f4e0623f1f158ae45e687fe059ac48c1

**Comment by akalin-keybase** [comment]
The behavior remains the same if `A int` is changed to `A R`, where `R` is a struct type. However, if `A int` is changed to `A []int`, it appears to work as expected.

**Comment by akalin-keybase** [comment]
BTW, thanks for your work on this library, and for looking at all the previous bugs I filed!

**Comment by ugorji** [comment]
Work as designed.

You say omitempty for one, and not for the other.  It worked. RecursiveEmptyCheck has no bearing.

RecursiveEmptyCheck just says "do more expensive checks to determine if struct, etc is empty. Look at the docs.

**Comment by ugorji** [comment]
See https://godoc.org/github.com/ugorji/go/codec#EncodeOptions

**Comment by akalin-keybase** [comment]
Ah, ok. However, I think I'm confused by the docs. There is:
```
Each exported struct field is encoded unless:
- the field is empty (empty or the zero value) and its tag specifies the "omitempty" option.
```

which implies that "omitempty" should just work for structs. But then why doesn't it work for a struct with a slice field set to `nil`?

There's also
```
The empty values (for omitempty option) are false, 0, any nil pointer or interface value, and any array, slice, map, or string of length zero.
```
which doesn't mention structs at all. I'm guessing this line is describing the old behavior?

I can't think of an easy way to describe when "omitempty" should work without `RecursiveEmptyCheck`. But I think at least that the sentence listing the "empty values" could be removed.

**Comment by akalin-keybase** [comment]
As a concrete example of my confusion, here's another example:

```
package main

import (
	"bytes"
	"testing"

	"github.com/ugorji/go/codec"
)

type S struct {
	A []int
}

type T1 struct {
	A []int `codec:",omitempty"`
}

type T2 struct {
	A S `codec:",omitempty"`
}

func TestDecodeOmitEmpty(t *testing.T) {
	t1 := T1{}

	var mh codec.MsgpackHandle

	var encoded1 []byte
	e1 := codec.NewEncoderBytes(&encoded1, &mh)
	e1.MustEncode(t1)

	if !bytes.Equal(encoded1, []byte{0x80}) {
		t.Fatalf("encoded1=%x", encoded1)
	}

	t2 := T2{}

	var encoded2 []byte
	e2 := codec.NewEncoderBytes(&encoded2, &mh)
	e2.MustEncode(t2)

	if !bytes.Equal(encoded2, []byte{0x80}) {
		t.Fatalf("encoded2=%x", encoded2)
	}
}
```

`omitempty` with an `[]int` field set to `nil` works as expected. I would also expect it to work with a struct with an `[]int` field set to `nil`, but it doesn't, even though checking that it's empty shouldn't require any dereferencing of the slice.

Am I misunderstanding something?

**Comment by ugorji** [comment]
Yes.

There's an easy way of checking if a value is empty:
- if slice, compare to nil (cheap)
- if number, compare to 0
- if bool, compare to false
- if string, compare to ""
- if array, compare to zero value of the array
- if struct, compare to zero value of struct. However, if a struct field is a slice, then we cannot compare to a zero value anymore (a struct with slice fields cannot be compared for equality).

Consequently, for a struct, we have to compare each field one by one to its zero value (recursively). This is potentially very expensive. This means that, only for a struct, the comparison to a zero value can potentially be expensive. 

Some users may not want to pay that cost. So - we provide a flag that says whether the user is willing to pay that cost or not. This is the "RecursiveEmptyCheck" flag.

Key message - if you have:

```go
type T struct {
  A []int
  B int
}

v1 = T{B:7}
v2 := T{A: []int{1,2}}

b1 := v1 == v2 // will not compile, as T is not comparable anymore
```

Hope this makes sense.

See https://golang.org/ref/spec#Comparison_operators (with selected notes from that section below)

- Struct values are comparable if all their fields are comparable. Two struct values are equal if their corresponding non-blank fields are equal.
- Slice, map, and function values are not comparable.

**Comment by ugorji** [comment]
See https://github.com/ugorji/go/blob/master/codec/helper.go#L1504 (the implementation of isEmptyStruct). 

It becomes expensive from line 1532: https://github.com/ugorji/go/blob/master/codec/helper.go#L1532

This is why we have that bool parameter: checkStruct (that is set based on the value of RecursiveEmptyCheck flag.

**Comment by akalin-keybase** [comment]
Thanks, this all makes sense!
