### ISSUE TITLE
Need RecursiveEmptyCheck as a tag

### ISSUE THREAD

**Issue by akalin-keybase** [ugorji/go#255]
Currently, it's impossible to express the following (assuming `Type1` and `Type2` are non-comparable types):

```
type T struct {
  Field1 *Type1 // shallow omitempty, i.e. omit only if nil
  Field2 *Type2 // deep omitempty, i.e. check recursively if Field2 is empty
}
```

The default behavior (`RecursiveEmptyCheck = false`) fails the requirement for `Field2`, but setting `RecursiveEmptyCheck = true` fails the requirement for `Field1`.

Ideally, there'd be a tag one could set on Field2 to turn on `RecursiveEmptyCheck`, but only on that field.

We actually already implemented this in our fork: https://github.com/keybase/go-codec/pull/10/files with an example use here: https://github.com/keybase/kbfs/blob/2aa3b930113603425f33e408b19c5d62c0b7ccb1/kbfsmd/root_metadata_v2.go#L61 .

Would love to get this into upstream. Would you take a PR for this?

**Comment by ugorji** [comment]
Sorry for the delayed response.

I am not comfortable with this change. The cost-benefit analysis doesn't skew quite right.

For example:

1. Each change must apply in code-generated and reflection-based paths
1. RecursiveEmptyCheck is already is not-so-widely used flag. I don't want to make it more "complicated".

I would rather that a fast solution is available, so that "RecursiveEmptyCheck" is always on.

**Comment by akalin-keybase** [comment]
I agree that ideally RecursiveEmptyCheck would always be on. Unfortunately, we use this library to encode signed payloads, and to verify a payload, we re-encode a payload, which must be bit-identical to the original payload for the signature to check. So for fields that had (non-recursively) `omitempty` previously, we need those to still be non-recursive.

Do you see any other solution other than us maintaining a fork? (which we don't really want to continue to do)

**Comment by ugorji** [comment]
I think a fork is your best option, if you MUST go down this path.

However, consider whether you really need this solution, and see if you can live with just one of the knobs. The RecursiveEmptyCheck is an option (as opposed to a struct tag - so it doesn't proliferate) and is a hint - that we will attempt to spend more cycles to check if the value is deeply empty.
