### ISSUE TITLE
Need some way to preserve unknown fields

### ISSUE THREAD

**Issue by akalin-keybase** [ugorji/go#258]
In our use of go-codec, we have a mixture of old clients and new clients.
If we add a field to a struct that is only used by old clients, we want
old clients to be able to update existing fields (i.e., read struct, change
field, write struct back out) while preserving any unknown fields, so that
it doesn't wipe out any added fields.

We implemented this ourselves (but not for code generation)
in https://github.com/keybase/go-codec/pull/8 . Basically if a struct obeys an interface UnknownFieldHandler, then our fork will call CodecSetUnknownFields with any unknown fields
it finds on decode (and the struct is expected to store that opaque value), and then
on encode it will call CodecGetUnknownFields to retrieve those unknown fields
to serialize them.

We'd like to upstream out changes if possible. I'd imagine this would be useful for other users,
too. What do you think?

**Comment by ugorji** [comment]
Can you share a test case showing that this doesn't work already?

**Comment by ugorji** [comment]
This is not an easy reproducer. Can you please provide a simple reproducer with only a go-codec dependency? It will allow me easily see the problem.

**Comment by akalin-keybase** [comment]
Oh, ok, try this:

```go
package main

import (
	"reflect"
	"testing"

	"github.com/ugorji/go/codec"
)

type InfoV1 struct {
	A int
}

type InfoV2 struct {
	A int
	B string
}

func TestUnknownFields(t *testing.T) {
	var h codec.MsgpackHandle
	var store []byte

	// Old client
	{
		info := InfoV1{A: 5}

		enc := codec.NewEncoderBytes(&store, &h)
		enc.MustEncode(info)
	}

	// New client
	{
		var info InfoV2
		dec := codec.NewDecoderBytes(store, &h)
		dec.MustDecode(&info)

		info.B = "new info"

		enc := codec.NewEncoderBytes(&store, &h)
		enc.MustEncode(info)

	}

	// Old client again
	{
		var info InfoV1
		dec := codec.NewDecoderBytes(store, &h)
		dec.MustDecode(&info)

		info.A = 6

		// Clobbers B field, since it's unknown to the old
		// client, which uses InfoV1.
		enc := codec.NewEncoderBytes(&store, &h)
		enc.MustEncode(info)
	}

	// New client again
	{
		var info InfoV2
		dec := codec.NewDecoderBytes(store, &h)
		dec.MustDecode(&info)

		expectedInfo := InfoV2{
			A: 6,
			B: "new info",
		}

		if !reflect.DeepEqual(info, expectedInfo) {
			t.Fatalf("info=%+v != expectedInfo=%+v", info, expectedInfo)
		}
	}
}
```

**Comment by ugorji** [comment]
Still thinking through this. Just have other things I need to finish, so I can think it through.

Please give me till next week. If you don't hear from me by August 28, please ping me.

**Comment by akalin-keybase** [comment]
No problem, thanks for your time!

**Comment by akalin-keybase** [comment]
Thanks for doing this! With this done, I'll try to get Keybase to unfork...

**Comment by ugorji** [comment]
@akalin-keybase Need to change the signature for MissingFielder, which will affect you. I want the signature to change to: CodecMissingFields() map[string]interface{}

This is a heads up before it happens. Right now, I am hoping that we are still within a month, so many people are not hip to this feature yet.

Thanks.
