### ISSUE TITLE
Clarify documentation that decode updates in-place and how to disable that

### ISSUE THREAD

**Issue by fjorgemota** [ugorji/go#264]
Hello!

Thanks for the nice library. It works really well and have a nice API :)

I'm opening this issue because I found a problem that seems...strange, especially for a library that helps with encoding/decoding of values. I'm working on a system that will use this library to encode and decode values that will be imported to the database and found that, on decode, some extra fields that were not defined by my code to the actual register were being inserted.

Debugging the problem on my code, I did not found any problems...I mean, all the expected fields were inserted correctly. But, testing more with the library options, I found the `DecodeOptions` struct that has some consistency sensitive fields (especially for `map`, which can be very dynamic):

- **MapValueReset** - [docs here](https://github.com/ugorji/go/blob/master/codec/decode.go#L188-L200);
- **DeleteOnNilValue** - [docs here](https://github.com/ugorji/go/blob/master/codec/decode.go#L202-L205);
- **SliceElementReset** - [docs here](https://github.com/ugorji/go/blob/master/codec/decode.go#L241-L245);

These options were simply...there, all `false` by default while having a really BAD impact on the code: Reusing the last map structures seem and causing fields found on old maps to appear again, on (I assume) new maps..

I know performance is important, but for a library with such a great responsability, prioritize performance over consistency seems really bad, even when there is really **no warning** on the documentation explaining the really bad effect of these options. 

I see two options to fix this:

- Negate these options (`SliceElementReset` turns into `DoSliceElementReset`) and, when `false`, we DISABLE it, so we can disable (instead of enable) them by default (should have some performance impact, BUT the consistency will be really better); 
- **WARN** about what these options do;

I really prefer the first option to avoid any mistakes..but it should be a breaking change so I understand if you would not like to apply on 1.x version to not break semantic versioning. Anyway, I think it should be important to at least warn the user with big letters to avoid these kind of problems.

Thanks for the great library anyway. Have a good day. =)

**Comment by ugorji** [comment]
For these options, I thought long and hard about what the default behavior should be, and provided knobs to tune the default behavior (for those who want or expect a different behavior - like yourself).

This is the first time that anyone has any feedback on the selected defaults.

With codec, we have been very careful to maintain backward compatibility. I would not change default behavior unless a lot of demand, and even then, it will be a tough call.

In this case, there isn't a large call to change things, meaning the defaults have worked well for many people for a lot of years. I will leave as is.

Thanks guys the detailed write up - much appreciated.

**Comment by fjorgemota** [comment]
Hey. Thanks for the answer. =)

> With codec, we have been very careful to maintain backward compatibility. I would not change default behavior unless a lot of demand, and even then, it will be a tough call.

I understand that point...and because of that reason I suggested to at least warn the user in the documentation about what these options does..

> In this case, there isn't a large call to change things, meaning the defaults have worked well for many people for a lot of years. I will leave as is.

I understand that phrase not as "meaning the defaults have worked well for many people for a lot of years", but as "a lot of people did not found these options and/or configured that and have not found these bugs, which are still probably hidden". On my case for example I was lucky enough to some of my test data trigger that behavior on the library and break the tests..while most of the other data did not do any breakage.

IDK really, I find is always good to favour consistency of performance, **especially** for a library that market itself as having a "drop-in mode" for the `encoding/json` library.

Even more, I'm a bit afraid of more of these options being added with performance being favoured instead of consistency...

Anyway, these are just my opinion. Thanks again for maintaining the library and good luck on your development.

**Comment by ugorji** [comment]
Got you. Fair enough.

Changing the defaults is not an option, for obvious reasons as you stated in your initial email. So, so this time, it's not worth debating what the appropriate option should have been. 

The plan is also to never have another major version - we always tried to keep the public interface small and tight so we can continue to support it while changing the internals. 

The only viable option, which you alluded to, is to make it clear in the documentation. I am very happy to do that. If you have some preferred text, I will consider it strongly. Or a PR so we can home in on the changes to make.

**Comment by ugorji** [comment]
Also, I don't favor performance over consistency. 

The model is that, by default, we update in place as much as possible. That's in the documentation. So if you pass a slice, we try to update that slice. If there are pointer, we try to update the pointer.

That's why we don't remove items from a map, and why we retrieve a key's value and update it

**Comment by fjorgemota** [comment]
Hey.

> The plan is also to never have another major version - we always tried to keep the public interface small and tight so we can continue to support it while changing the internals.

Even in the long term? I don't see any problems about having a major version after a long time supporting 1.x...To fix these things on public interface and maybe to bring other improvements, for example.

> The only viable option, which you alluded to, is to make it clear in the documentation. I am very happy to do that. If you have some preferred text, I will consider it strongly. Or a PR so we can home in on the changes to make.

I thought a bit about adding a `dev` mode which would need to be disabled and would be able to bring attention to these options..maybe with an one-time warning if some of these cases were detected...I mean, it would need to be easy to disable but could help a developer to detect such cases..no idea.

About the documentation...I throught about updating the [Go Codec Primer](http://ugorji.net/blog/go-codec-primer). Not really sure about how many developers read the godoc of the package..

> The model is that, by default, we update in place as much as possible. That's in the documentation. So if you pass a slice, we try to update that slice. If there are pointer, we try to update the pointer.

Yeah, I guess that's feature is pretty okay, at least, it seems a bit, not sure if `encoding/json` resets everything everytime...If it resets, for sure that feature could be available as an (non-default) option, IMO.
 
What afraids me more is the fact of the **internal** reuse of these data structures by the system.

For example, imagine the following struct:

```go
type Limit struct {
	Values  map[string]float64 `json:"values"`
}

type Habilitation struct {
	Limits []Limit `json:"limits"`
}
```

Please note that I omitted fields for brevity, but these are the problematic ones...On my case, I was passing a re-used variable from a Pool with the type `Habilitation`  (with `Limits` with zero length (aka `hab.Limits = hab.Limits[:0]`, for example)) to a codec Decoder and because of that re-use `Values` had a field that was **not** present on the original JSON readed, but **was** present on a JSON readed before. Not 100% sure about how this could happen, but seems related to these fields I mentioned. Am I clear?

**Comment by ugorji** [comment]
No to "dev mode". 

The documentation is the only viable option that I am comfortable with.

If you provide some updates to the godoc and to the primer, I can incorporate them.

I understand what you are saying. Now you know how the library works, you can work accordingly. But yes - if things are not clear, we should make it clearer in the docs.

**Comment by ugorji** [comment]
I just looked at the documentation again, and see that it is clearly spelled out, and in the right place (under the Decode function). There isn't any further need to *document* this again (at the high level - except for a bullet point under features, which I am happy to add). 

Look at https://godoc.org/github.com/ugorji/go/codec#Decoder.Decode (that's where the docs are). I will clarify it, by making it clear what UPDATE means, and stating that the DecodeOptions (MapValueReset and SliceElementReset) available on each handle can be used to modify the default behavior.

Hopefully this is sufficient for you. I think it achieves what you want (make the docs clear on the philosophy and how to workaround it, at both package level and function level), while maintaining the style I'm comfortable with (crisp docs for a crisp package).

**Comment by fjorgemota** [comment]
Oh, no problem. Thank you for the update =)
