### ISSUE TITLE
Backwards compatibility for time using msgpack encoding and decoding

### ISSUE THREAD

**Issue by Trial97** [ugorji/go#269]
Can you please recommend some backwards compatibility \:
If you encode the time in a version before the commit [5a66da2](https://github.com/ugorji/go/commit/5a66da2e74afec77056667aacd61e97b6ea8f661), how can we decode it in the commits after it? The used encoder is msgpack.
The error is \: Error executing command: msgpack decode error [pos 131]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15

**Comment by ugorji** [comment]
@Trial97 That commit didn't make any changes to time encoding for msgpack.

**Comment by Trial97** [comment]
Sorry for the inconveniences the commit that the change happened is\: [debb8e2](https://github.com/ugorji/go/commit/debb8e2d2e8bd8cf1e9b6d806cf5e58df86b970c), not the one mentioned before.

**Comment by Trial97** [comment]
That flag is only to migrate the data?

**Comment by ugorji** [comment]
This the best I can do. 

You might have to read with one handle configured one way, and write back out with another handle configured the other way. This allows you migrate.
