### ISSUE TITLE
Q: Decode value in a field into different types depending on a value in another field

### ISSUE THREAD

**Issue by ken5scal** [ugorji/go#277]
This question is a bit similar to #138.
I want to decode a value which would have a different structure based on another field.
For example, say I have `SomeObject` in which `Statement` field can use multiple structures depending on `Fmt` value. In other words, you would not know the structure of `Statement` until `Fmt` value is evaluated. Would `ugorji/go/codec` be able to carry out such decoding?

```
type SomeObject struct {
	Fmt string `codec:"fmt"`
	Statement  {the struct can be either StmtOne or StmtTwo based on fmt} `codec:"stmt"`
}

type StmtOne struct {
	Ver      string `codec:"ver"` 
	Response []byte `codec:"response"` 
}

type StmtTwo struct {
	X5c      string `codec:"x5c"` 
	Sigs []byte `codec:"signatures"` 
}
```

**Comment by ugorji** [comment]
You can make this work, but it is not natively supported by the library. This means you have to write some code to do this, leveraging what the library provides.

Currently, the library assumes that you know the structure of what you want to decode into, or it will allow you decode into a generic container (e.g. map, slice, etc). The only escape hatch is the "Raw" type.

Your best bet might be one of the following:

- peep into Fmt, and based on that, decode into the appropriate value. This requires that you know the format you are working with.
- decode into struct { Fmt string; Raw codec.Raw }. This way, we get the raw bytes, and then do a second pass to decode the raw bytes into an appropriate structure. See https://godoc.org/github.com/ugorji/go/codec#Raw

Hope this helps.
