### ISSUE TITLE
should this work, at least this used to

### ISSUE THREAD

**Issue by ruz** [ugorji/go#278]
```
package main

import (
	"bytes"
	"fmt"
	"github.com/ugorji/go/codec"
)

func main() {
	var w bytes.Buffer
	encoder := codec.NewEncoder(&w, new(codec.CborHandle))
	err := encoder.Encode(uint32(123456))
	err = encoder.Encode(uint32(123456))
	fmt.Printf("error: %+v\n", err)
}
```

This is used to work with older commits.

**Comment by ugorji** [comment]
Thanks. Will look at it this week.

**Comment by ugy** [comment]
Same problem here ! Calling Encode only work the first time and return an "index out of range" error afterward. It used to work fine before.
Fixed it by calling encoder.Reset() each time I call encoder.Encode but not sure it's normal.
