### ISSUE TITLE
msgpack: RawToString not honored when decoding raw bytes into empty interface{}

### ISSUE THREAD

**Issue by diacone** [ugorji/go#293]
When I upgraded to v1.1.4 all strings (represented as interface{} in the code) are now decoded as `[]unit8` regardless of `RawToString` option. The only setting which helps is to use `WriteExt`. See the code below to demonstrate that. That requires to have different handles for encoding and decoding if I don't want to have WriteExt enabled for encoding (specifically because 3rd party apps does not necessarily understand them; e.g. fluentd).

Is this a bug or am I doing something wrong? It used to work with older version.

```
package main

import (
	"bytes"
	"fmt"

	"github.com/ugorji/go/codec"
)

func main() {
	m := map[string]interface{}{"key": "value"}

	var res interface{}

	res = noWriteExt(m)
	fmt.Printf("%v\n", res)

	res = writeExt(m)
	fmt.Printf("%v\n", res)

}

func noWriteExt(v interface{}) interface{} {
	h := new(codec.MsgpackHandle)
	h.RawToString = true // doesn't have any effect

	var b bytes.Buffer
	enc := codec.NewEncoder(&b, h)
	enc.Encode(v)

	var mm map[string]interface{}
	codec.NewDecoder(&b, h).Decode(&mm)
	return mm
}

func writeExt(v interface{}) interface{} {
	h := new(codec.MsgpackHandle)
	h.RawToString = true // doesn't have any effect

	var b bytes.Buffer
	enc := codec.NewEncoder(&b, h)
	enc.Encode(v)

	// this works ...
	h.WriteExt = true

	var mm map[string]interface{}
	codec.NewDecoder(&b, h).Decode(&mm)
	return mm
}
```

**Comment by ugorji** [comment]
Thanks for the bug report. Will look into it by tomorrow.
