### ISSUE TITLE
Unable to decode the full object (map of slices)

### ISSUE THREAD

**Issue by kprimice** [ugorji/go#305]
I want to be able to save different sorts of maps into a file and load them later. I use this code:

```go    
func save(path string, v interface{}) error {
	var h codec.Handle = new(codec.MsgpackHandle)

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	w := bufio.NewWriter(f) 
	e := codec.NewEncoder(w, h)

	if err := e.Encode(v); err != nil {
		return err
	}
	w.Flush()
	f.Close()
	return nil
}

func load(path string, v interface{}) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	var h codec.MsgpackHandle
	d := codec.NewDecoder(f, &h)
	d.Decode(v)
	return nil
}
```

It works properly for a map of struct (`map[uint32]*struct`). However it does not save/load the full map for a map of slice (`map[uint32][]uint32`).

The `save` function seems to work properly because the size of the file is always the same. However the `load` function loads a random number of elements each time.

**Comment by ugorji** [comment]
I don't know enough about what you are doing to assist you.

Please create a reproducer that I can run via "go test" or "go run", and I can reproduce it in-house and fix.

Ping me here if/when you do and I will re-open this issue.
