### ISSUE TITLE
Decoder returns []uint8 for string value in a map

### ISSUE THREAD

**Issue by babartareen** [ugorji/go#31]
Here is the code I am using to encode/decode the maps. For my tests I am passing in a map with string key and value. The decoded map contains string key but []uint8 as value. I expect it to return the same map structure which was encoded.

  **Enocde / Decode code**

```
func encode(msg map[string]interface{}) ([]byte, error) {
    var encoded []byte
    enc := codec.NewEncoderBytes(&encoded, &mh)
    err := enc.Encode(msg)
    if err != nil {
        return nil, err
    }

    return encoded, nil
}

func decode(encoded []byte) (map[string]interface{}, error) {
    var decoded map[string]interface{}
    dec := codec.NewDecoderBytes(encoded, &mh)
    err := dec.Decode(&decoded)
    if err != nil {
        return nil, err
    }
    return decoded, nil
}
```

**Test**

```
import (
    . "gopkg.in/check.v1"
    "testing"
)

// Hook up gocheck into the "go test" runner.
func Test(t *testing.T) {
    TestingT(t)
}

type S struct{}
var _ = Suite(&S{})
func (s *S) TestEncodeDecode(c *C) {
    msg := make(map[string]interface{})
    msg["Hello"] = string("world")
    encoded, err := encode(msg)
    c.Assert(err, IsNil)
    c.Assert(encoded, NotNil)
    decoded, err := decode(encoded)
    c.Assert(err, IsNil)
    c.Assert(decoded, DeepEquals, msg)
}
```

**Here is the output of the test run.**

> FAIL: test.go:27: S.TestEncodeDecode
> 
> test.go:35:
>     c.Assert(decoded, DeepEquals, msg) ... obtained map[string]interface {} = map[string]interface
> {}{"Hello":[]uint8{0x77, 0x6f, 0x72, 0x6c, 0x64}} ... expected
> map[string]interface {} = map[string]interface {}{"Hello":"world"}
> 
> OOPS: 0 passed, 1 FAILED
> --- FAIL: Test (0.00 seconds) FAIL

**Comment by cvermilion** [comment]
I just ran into this issue, and I'm confused why it isn't a bug. MessagePack has defined string types, so if we're decoding a fixmap, say, with string keys and values, into an `interface{}`, why unpack the value as a `[]uint8` instead of a `string`? It seems like that would be the sensible default behavior.

MessagePack has both string and binary types, right, so this setting means that the string family and binary family are either both decoded to strings, or both decoded to bytes, no?

**Comment by ugorji** [comment]
There's 2 versions of messagepack. The newer one has 2 distinct types, but until recently, there was just one type. The flags in MessagePackHandle are sufficient to clearly describe your intent (ie are you compatible with the old version where we default to []byte and you can configure it to string) or do you want us to default to new version behaviour throughout (which you can configure with the WriteExt option).

**Comment by cvermilion** [comment]
Ah, thanks for the info! I'm new to MessagePack and the fact that there was a schema evolution was tucked away at the bottom of their docs.

I'm still not seeing what I would expect even with `WriteExt = true`, though:

```go
var h *codec.MsgpackHandle = new(codec.MsgpackHandle)
h.WriteExt = true
x := append([]byte{0xa3}, []byte("bar")...) // fixstr encoded
dec := codec.NewDecoderBytes(x, h)
var y interface{}
dec.Decode(&y)
fmt.Println("Decoded string to:", y) // [98 97 114]
```

I would have expected that to print `bar`. Am I still missing something?

**Comment by cvermilion** [comment]
Hmm, if I set `WriteExt=true` *and* `RawToString=true`, then string types are decoded as strings and bin types are decoded as `[]byte`. I think that will do for my application but that wouldn't have been obvious from the [docs](https://godoc.org/github.com/ugorji/go/codec#MsgpackHandle).
