### ISSUE TITLE
Go Mod Issue

### ISSUE THREAD

**Issue by 1995parham** [ugorji/go#318]
I have got the following error by using the go module:

```
        github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (/home/parham/Documents/Go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
        github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/home/parham/Documents/Go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)
```

I think there is no need to have `go.mod` in the project root.

**Comment by dalu** [comment]
same here, annoying af.
How do you manually solve this?
Freaking go mod

**Comment by sachinagada** [comment]
Try adding `github.com/ugorji/go v1.1.7` to your go.mod file.

**Comment by ugorji** [comment]
Please read https://github.com/ugorji/go/issues/299

It's important to know the context and history, so you know what influenced the decision to make the committed fix. This also helps you make informed comments or offer informed changes.

I'm open to whatever is the best path moving forward, and am fully open to better ways forward.
