### ISSUE TITLE
Add TODOs badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [ugorji/go#330]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/ugorji/go)](https://www.tickgit.com/browse?repo=github.com/ugorji/go)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/ugorji/go)](https://www.tickgit.com/browse?repo=github.com/ugorji/go)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by ugorji** [comment]
Thanks for the suggestion.

Currently, I don't use TODO's much. I'm actually surprised there's so many. I will look through to get them removed/resolved.
