### ISSUE TITLE
Data race in release 1.1.11

### ISSUE THREAD

**Issue by hansg-axis** [ugorji/go#336]
We are using the msgpack part of this project and when I updated to 1.1.11 and ran our tests several data race errors were detected, see the attached file for stack traces. This error never happened with 1.1.10 and happens every time I'm running our tests with 1.1.11.
[msg_pack_data_race.txt](https://github.com/ugorji/go/files/5372593/msg_pack_data_race.txt)

**Comment by ugorji** [comment]
taking a look now

**Comment by ugorji** [comment]
Thanks. I have identified the issue. I will send out a fix. Please test it out and let me know that it fixes your issue, and I will cut a new release soon after I hear from you.
