### ISSUE TITLE
Tag v1.1.5-pre does not exist anymore

### ISSUE THREAD

**Issue by rbretecher-fcms** [ugorji/go#337]
Hello,

Since today, we are experiencing build issues with our application and it seems that it's because the tag `v1.1.5-pre` of your Go module is missing. This module is an indirect dependency used by Gin and we're not sure we can upgrade Gin to use a later version.

As I'm not sure this is the issue, could you tell me if you recently removed this tag ?

Thanks for your help.

**Comment by gngchrs** [comment]
fixed mine with

`go mod edit --replace github.com/ugorji/go@v1.1.5-pre=github.com/ugorji/go@v1.1.6`

**Comment by ugorji** [comment]
This was a pre-release tag that I was using to test out modules over a year ago. I was confident (incorrectly) that no one depended on it. My apologies.

I just took a look at Gin and it's [go.mod](https://github.com/gin-gonic/gin/blob/master/go.mod) references v1.1.6. 

Maybe there's something else that is dragging v1.1.5-pre? Im hoping we can track that down quickly, before having to resort to re-creating the tag.

**Comment by ugorji** [comment]
Also checked the [go.sum](https://github.com/gin-gonic/gin/blob/master/go.sum) file, and it references v1.1.7

Correction: the [go.mod](https://github.com/gin-gonic/gin/blob/master/go.mod) also references v1.1.7

Not sure why you are seeing v1.1.5-pre . Can you please try to deduce further?

**Comment by gngchrs** [comment]
@ugorji mine came from http-swagger, whose dependency graph was like below. 

<img width="1068" alt="Screenshot 2020-10-14 at 08 23 32" src="https://user-images.githubusercontent.com/3910877/95951427-b1246380-0df6-11eb-8487-98fc9db82c3c.png">

**Comment by rbretecher-fcms** [comment]
@ugorji  Actually, I built a dependency graph graph using depth tool ( https://github.com/KyleBanks/depth ) and the only module that uses your moduse is Gin so I assumed this was coming from Gin.

@gngchrs Could you tell me how you managed to build this dependency graph ?

**Comment by gngchrs** [comment]
@rbretecher-fcms I only have github.com/swaggo/http-swagger as a dependency in my go.mod, and my builds started failing yesterday. The image posted above is what I see when the build fails.

**Comment by rbretecher-fcms** [comment]
@gngchrs I see, thanks for you answer :) 

I just upgraded the module and this finally solved my issue :
```bash
go get -u github.com/ugorji/go
```

**Comment by ugorji** [comment]
I found a way to restore the tag. Luckily, github release allowed me have a hanging release, and still held onto the tag. I have now restored v1.1.5-pre. Please retry and confirm.

Still, let's have the other users upgrade, so that I can eventually remove this. I was hoping pkg.go.dev could tell who is using a specific version, but I couldn't find that.

**Comment by ugorji** [comment]
See https://github.com/ugorji/go/tree/v1.1.5-pre
