### ISSUE TITLE
relocation target reflect.typedmemclr not defined

### ISSUE THREAD

**Issue by bhaskarsantoshk** [ugorji/go#340]
I was trying to build a go binary for centOS in a docker container, It's giving the following error:

# command-line-arguments
github.com/ugorji/go/codec.rvSetDirect: relocation target reflect.typedmemclr not defined
github.com/ugorji/go/codec.rvSetDirectZero: relocation target reflect.typedmemclr not defined

**Comment by ugorji** [comment]
This is a weird issue - it seems something with the docker environment is stripping some things.

Nevertheless, I updated to code to use the runtime implementations directly where possible, instead of using the reflect stubs. Maybe that fixes things for you.

Please check and lemme know.
