### ISSUE TITLE
Latest update broke the codecgen tool

### ISSUE THREAD

**Issue by vanackere** [ugorji/go#343]
Hi,

It looks like the latest update broke the codecgen tool:

`./codecgen-pkg-1993.generated.go:127:15: not enough arguments in call to codec.Gen
        have (*bytes.Buffer, string, string, string, bool, *codec.TypeInfos, []reflect.Type...)
        want (io.Writer, string, string, string, bool, *bool, *bool, *bool, *codec.TypeInfos, ...reflect.Type)
`

From a quick look the template genFrunPkgTmpl in vendor/github.com/ugorji/go/codec/codecgen/gen.go was not updated for the 3 new *bool arguments

**Comment by ugorji** [comment]
I was sure it works, as we test these always on each check in.

However, I also looked at the source on github, and it's reflected. See  
https://github.com/ugorji/go/blob/master/codec/codecgen/gen.go#L103  
https://github.com/ugorji/go/blob/master/codec/gen.go#L261

I think this is a user error - probably something about how it was vendored i.e. see the path you posted in the message is a vendor path.

**Comment by vanackere** [comment]
You're right, somehow the dependency to github.com/ugorji/go/codec/codecgen in my repository was not properly upgraded in go.mod.
I'll investigate... sorry for the wrong report !
