### ISSUE TITLE
Issue with Swagger 1.6.5, 1.6.4, 1.6.3

### ISSUE THREAD

**Issue by chetan-apty** [ugorji/go#349]
I am facing an issue after recent changes happened with ugorji. On downloading github.com/swaggo/swag 1.6.5 version, there is an dependency error thrown as shown below:
github.com/swaggo/swag@v1.6.5 requires
        github.com/swaggo/gin-swagger@v1.2.0 requires
        github.com/ugorji/go@v1.1.5-pre requires
        github.com/ugorji/go/codec@v1.1.5-pre: reading github.com/ugorji/go/codec/codec/go.mod at revision codec/v1.1.5-pre: unknown revision codec/v1.1.5-pre

![image](https://user-images.githubusercontent.com/51608147/101354389-165a7980-38bb-11eb-9a95-280ddca17d2e.png)

Current Go version installed is 1.13.5

If you could help us out in resolving this issue, that would be great!!

**Comment by ugorji** [comment]
I just re-added a tag for codec/v1.1.5-pre - see https://github.com/ugorji/go/tree/codec/v1.1.5-pre

Try again and see if it resolves your issue.

If not, this has to be followed upstream with gin-swagger or swag, as they seemingly (directly or indirectly) depended on a pre-release version, and need to upgrade/update.
