### ISSUE TITLE
ambiguous import: found github.com/ugorji/go/codec in multiple modules

### ISSUE THREAD

**Issue by yhaoyan** [ugorji/go#362]
git.code.oa.com/PostgreSQL/shark/src/shark/controller/account tested by
        git.code.oa.com/PostgreSQL/shark/src/shark/controller/account.test imports
        git.code.oa.com/cdb_common/mockdb imports
        github.com/pingcap/tidb/tidb-server imports
        github.com/pingcap/pd/client tested by
        github.com/pingcap/pd/client.test imports
        github.com/pingcap/pd/server imports
        github.com/pingcap/pd/pkg/etcdutil imports
        go.etcd.io/etcd/etcdserver imports
        go.etcd.io/etcd/etcdserver/api/v2discovery imports
        go.etcd.io/etcd/client imports
        github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (/home/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
        github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43 (/home/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20190204201341-e444a5086c43)

**Comment by ugorji** [comment]
Please see https://github.com/ugorji/go/blob/master/FAQ.md#resolving-module-issues

The owner of the package should update to a version of github.com/ugorji/go/codec above v1.1.5, which was released around July 2019. The latest release is the latest and greatest.
