### ISSUE TITLE
Incorrect codecgen code is generated

### ISSUE THREAD

**Issue by mxmauro** [ugorji/go#372]
Hi, I attached a [sample project](https://github.com/ugorji/go/files/8887017/test.zip) in order to show the issue.

The problem appears when a package tries to use code generated in other package.

To reproduce the issue follow this steps:

1. Run `go mod tidy` and  `go mod vendor` to download the dependencies. (vendoring is not required but used here to encapsulate the test)
2. Run `codecgen -nx -o test2_codec.go test2.go` in the `test2` subdirectory.
3. Run `codecgen -nx -o test_codec.go test.go` in the "root" directory.
4. Run `go test`
 
You will get something like this:

```bash
# test.com/test
.\test_codec.go:77:11: yysf5.CodecEncodeSelf undefined (type **test2.A has no field or method CodecEncodeSelf)
.\test_codec.go:101:11: yysf7.CodecEncodeSelf undefined (type **test2.A has no field or method CodecEncodeSelf)
.\test_codec.go:227:12: yysf4.CodecEncodeSelf undefined (type **test2.A has no field or method CodecEncodeSelf)
.\test_codec.go:254:12: yysf5.CodecEncodeSelf undefined (type **test2.A has no field or method CodecEncodeSelf)
FAIL    test.com/test [build failed]
```

I was able to patch it by replacing [this](https://github.com/ugorji/go/blob/master/codec/gen.go#L1631) line:

```golang
if ti2.flagSelfer {
```

with:

```golang
if ti2.flagSelfer || (isptr && ti2.flagSelferPtr) {
```

but not sure if the right thing to do.

Kind regards,
Mauro.

**Comment by mxmauro** [comment]
Uploaded test to [my github repo](https://github.com/mxmauro/ugorji_codec_test).

**Comment by ugorji** [comment]
Thanks so much for catching this. Your intuition was spot on. Fixed, and it will push it soon.

**Comment by mxmauro** [comment]
Excellent. I have other fixes to tell you but give me some time to create them (because Holidays). For e.g., this the attached code
![image](https://user-images.githubusercontent.com/1683070/208211251-c582d3f2-bda5-4fa0-b761-db9505c282e9.png)

When zerocopy is active, no idea why a `[32]byte` object and a `type Address [32]byte` generates different flows and one of them leaves the array with zeroes.
