### ISSUE TITLE
Unable to Decode bytes | CborHandle not working as expected

### ISSUE THREAD

**Issue by HardCodeProgrammer** [ugorji/go#373]
### **Did you read the documentation?** 
Yes

### **What are you trying to do?**
I'm reading a file that has data encoded in CBOR format and passing the bytes to decode
More specifically I'm

>  Decoding without knowing what is in the stream

as said [in the primer](http://ugorji.net/blog/go-codec-primer)  

**_Code_**
```go
// Deserialize the data
//
// Converts CBOR byte array from a file to a Data container
//  d []byte - `The data read from a file`
//
// Returns
//  data interface{} - `The deserialized data`
func Decode(d []byte) (data any) {
	var _d any
	if d == nil {
		return nil
	}

       	fmt.Println(d)

	err := codec.NewDecoderBytes(d, new(codec.CborHandle)).Decode(&_d)

	if CheckErr(err) {
		panic(err)
	}

	println(_d)

	return _d
}
```

_**Input passed (`d []byte`)**_ 
```
[163 102 100 97 116 97 95 51 161 102 100 101 112 116 104 50 161 102 100 101 112 116 104 51 111 86 97 108 117 101 32 111 102 32 100 97 116 97 32 51 102 100 97 116 97 95 49 161 102 100 101 112 116 104 50 161 102 100 101 112 116 104 51 111 86 97 108 117 101 32 111 102 32 100 97 116 97 32 49 102 100 97 116 97 95 50 161 102 100 101 112 116 104 50 161 102 100 101 112 116 104 51 111 86 97 108 117 101 32 111 102 32 100 97 116 97 32 50]
```
_**Output**_
```shell
$ go run .
> [163 102 100 97 116 97 95 51 161 102 100 101 112 116 104 50 161 102 100 101 112 116 104 51 111 86 97 108 117 101 32 111 102 32 100 97 116 97 32 51 102 100 97 116 97 95 49 161 102 100 101 112 116 104 50 161 102 100 101 112 116 104 51 111 86 97 108 117 101 32 111 102 32 100 97 116 97 32 49 102 100 97 116 97 95 50 161 102 100 101 112 116 104 50 161 102 100 101 112 116 104 51 111 86 97 108 117 101 32 111 102 32 100 97 116 97 32 50]
(0x8fbf60,0xc000089110)
```

_**Expected Output**_ [CBOR Playground](https://cbor.me/)
![image](https://user-images.githubusercontent.com/75080162/177611201-4ee5323e-05ef-441c-bc49-4578cea36301.png)

Please Help 🙏 @ugorji 

**EDIT**: I tried to decode a sample json data using JsonHandle and it works perfectly.

**Comment by ugorji** [comment]
Hard for me to reproduce this and know if this is a valid error or user error. 

Can you please post a reproducer (main.go or main_test.go) that I can just run with "go run main.go" or "go test".

Thanks.

**Comment by ugorji** [comment]
if you post something here, just tag me using @ugorji and I will take another look.

**Comment by ugorji** [comment]
@HardCodeProgrammer ^^
