### ISSUE TITLE
SAST: coverity scan : Operands don't affect result

### ISSUE THREAD

**Issue by raghvendra-dixit** [ugorji/go#374]
As part of coverity scan , following is observed in 
Details: The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In github.​com/ugorji/go/codec.​mpdesc(byte, string): An operation with non-constant operands that computes a result with constant value.
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/93790023/182472790-7451574a-8e5f-4ef2-ab16-ce949b326818.png">

**Comment by ugorji** [comment]
Leave as is for code cleanliness reasons. At worst, it's redundant but removing this check causes a change to the constants to introduce a bug.
