### ISSUE TITLE
SAST: coverity scan : Operands don't affect result

### ISSUE THREAD

**Issue by raghvendra-dixit** [ugorji/go#375]
As part of coverity scan in file `msgpack.go`:
Details:
1. The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In github.​com/ugorji/go/codec.​msgpackDecDriver.​DecodeInt64(int64): An operation with non-constant operands that computes a result with constant value
2. The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In github.​com/ugorji/go/codec.​msgpackDecDriver.​DecodeNaked(): An operation with non-constant operands that computes a result with constant value.
3. The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In github.​com/ugorji/go/codec.​msgpackDecDriver.​DecodeUint64(uint64): An operation with non-constant operands that computes a result with constant value.
4. The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In github.​com/ugorji/go/codec.​mpdesc(byte, string): An operation with non-constant operands that computes a result with constant value

Screenshots:
1. 
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/93790023/182473250-b49c0b78-e25d-4a9b-8fe4-553deee3420f.png">
2. 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/93790023/182473404-acf38451-f5fb-4526-bcf9-9760de932bca.png">
3. 
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/93790023/182473521-b6927330-a243-4ba7-bbbd-a791fc53e94a.png">
4. 
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/93790023/182473621-7f489d04-4e86-4e23-bfaa-feae7176ad43.png">

**Comment by ugorji** [comment]
Outdated codebase. Please re-run.
