### ISSUE TITLE
Coverity scan - Operands don't affect result

### ISSUE THREAD

**Issue by raghvendra-dixit** [ugorji/go#376]
File: https://github.com/ugorji/go/blob/master/codec/json.go
Details:The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In github.​com/ugorji/go/codec.​jsonParseInteger([]byte): An operation with non-constant operands that computes a result with constant value

screenshot:
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/93790023/182475390-074540be-8fee-4bc7-bc19-056896336f06.png">

**Comment by ugorji** [comment]
Outdated codebase. Please re-run.
