### ISSUE TITLE
Coverity Scan - Explicit null dereferenced

### ISSUE THREAD

**Issue by raghvendra-dixit** [ugorji/go#378]
File: https://github.com/ugorji/go/blob/master/codec/encode.go
Details: 
A null pointer exception will occur.

In github.​com/ugorji/go/codec.​Encoder.​encode(interface{}): Dereference of an explicit null (nil) value ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))
Screenshot:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/93790023/182485108-3f9b2ead-472a-4c96-85d4-f30f23e3424f.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/93790023/182485143-c2042146-5ae6-4a23-9eb3-deaa092d8e15.png">
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/93790023/182485174-03751ebc-8f84-48bc-a86f-54b4656f05ea.png">

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/93790023/182485058-b42a3ded-f3a6-440d-a7e5-aaa548ac7c8d.png">

**Comment by ugorji** [comment]
outdated branch.
