### ISSUE TITLE
Coverity Scan - Logically dead code

### ISSUE THREAD

**Issue by raghvendra-dixit** [ugorji/go#379]
File : https://github.com/ugorji/go/blob/master/codec/encode.go
Error - 
The indicated dead code may have performed some action; that action will never occur.

In github.​com/ugorji/go/codec.​Encoder.​encode(interface{}): Code can never be reached because of a logical contradiction ([CWE-561](http://cwe.mitre.org/data/definitions/561.html))

Screenshot:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/93790023/182485364-7301cdaf-c65d-4815-ac3d-24ee50d3eac4.png">

**Comment by ugorji** [comment]
This is not a valid bug. We treat uint and uint64 as different types, even if they end up being the same type. Consequently, we should check both, else we have to check first if running on 32 or 64 bit. At worst case, this is redundant. But it destroys the code to code around this check. Ignoring.
