### ISSUE TITLE
Coverity Scan - Logically Dead code

### ISSUE THREAD

**Issue by raghvendra-dixit** [ugorji/go#380]
File : https://github.com/ugorji/go/blob/master/codec/decode.go
Error :The indicated dead code may have performed some action; that action will never occur.
In github.​com/ugorji/go/codec.​Decoder.​kMap(*github.​com/ugorji/go/codec.​codecFnInfo, reflect.​Value): Code can never be reached because of a logical contradiction ([CWE-561](http://cwe.mitre.org/data/definitions/561.html))
Screenshot:
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/93790023/182485914-b364d303-94e7-40d1-9ca1-44a5edb12efe.png">

**Comment by ugorji** [comment]
Reference is not in latest code. Please re-run.
