### ISSUE TITLE
unable to restore original data while using map[string]interface{}

### ISSUE THREAD

**Issue by phith0n** [ugorji/go#384]
Hi, I have to use `codec` to receive JSON format data from clients, and save it into database in Msgpack format. Then restore the object to JSON format and send back to clients if they need it.

The data struct likes that:

```go
type Sample struct {
	KV map[string]interface{} `json:"kv" codec:"kv"`
}
```

I use a simple code to demostrate what I have to do:

```go
package model

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"github.com/ugorji/go/codec"
	"testing"
)

type Sample struct {
	KV map[string]interface{} `json:"kv" codec:"kv"`
}

func TestModel(t *testing.T) {
	var data = `{"kv": {"a": "b", "c": 1, "d": {"e": "f"}}}`
	var mh codec.MsgpackHandle
	var jh codec.JsonHandle

	// first step, decode data as JSON format
	var s Sample
	var dec = codec.NewDecoderString(data, &jh)
	assert.Nil(t, dec.Decode(&s))

	// second step, encode data as Msgpack format
	var data2 []byte
	var enc = codec.NewEncoderBytes(&data2, &mh)
	assert.Nil(t, enc.Encode(&s))

	// 3rd step, decode data as Msgpack format
	var s2 Sample
	dec = codec.NewDecoderBytes(data2, &mh)
	assert.Nil(t, dec.Decode(&s2))

	// 4th step, encode data as JSON format
	var data3 []byte
	enc = codec.NewEncoderBytes(&data3, &jh)
	assert.Nil(t, enc.Encode(&s2))

	// full flow is [json decode]->[msgpack encode]->[msgpack decode]->[json encode]
	fmt.Println(string(data3))
}
```

The full data flow is:

[![](https://mermaid.ink/img/pako:eNplj7FuwjAQhl_ldDMeCFsGWNqtUzsw4AzX-EJCYx84Z1UI8e44DZGC6sn-7_s_nW9Yi2Mssenlt24pKnx82gD5OFJaH06DBGgketIpqcCYv9DxWDVmC_J9WufUD8cz1T_AYR6MheIw5wtLUS34F1Ex618tm3-LbKrFmiDGwL69Pl8U3MQARYYgCnxJ1O-yW6YBrtBzdnUu__02mixqy54tlvnquKHUq0Ub7hlN51zid9epRCwb6gdeISWVr2uosdSYeIbeOjpG8k_q_gBvlnWY)](https://mermaid.live/edit#pako:eNplj7FuwjAQhl_ldDMeCFsGWNqtUzsw4AzX-EJCYx84Z1UI8e44DZGC6sn-7_s_nW9Yi2Mssenlt24pKnx82gD5OFJaH06DBGgketIpqcCYv9DxWDVmC_J9WufUD8cz1T_AYR6MheIw5wtLUS34F1Ex618tm3-LbKrFmiDGwL69Pl8U3MQARYYgCnxJ1O-yW6YBrtBzdnUu__02mixqy54tlvnquKHUq0Ub7hlN51zid9epRCwb6gdeISWVr2uosdSYeIbeOjpG8k_q_gBvlnWY)

But the problem is that, my input JSON data is `{"kv": {"a": "b", "c": 1, "d": {"e": "f"}}}`, and the result JSON data is `{"kv":{"d":{"e":"Zg=="},"a":"Yg==","c":1}}`, which is not equal to the original content.

I'm not sure if it is a bug in `codec`. But is there any solution to satisfy my situation (let input data same as output data)? Thanks~

**Comment by ugorji** [comment]
The problem is that by default, MsgpackHandle honors the old msgpack spec. To honor the new spec that differentiates well between string and bytes, use 
``` 
mh.WriteExt = true
```

I tested it, and it solves your issue.
