### ISSUE TITLE
mem leak?

### ISSUE THREAD

**Issue by jank1369** [ugorji/go#401]
<img width="889" alt="image" src="https://github.com/ugorji/go/assets/20797373/483b8297-1491-469f-9944-8371d070edf1">

it seems the kString() func  has mem leak?

**Comment by ugorji** [comment]
Not clear just from this screen shot. 

Decoder.kString -> DecoderstringZC -> Decoder.string 

If interning = true, then a map of strings is kept, which could grow if the strings are constantly random.

Nothing here suggests a memory leak. Please re-open if you have more information suggesting an issue.
