### ISSUE TITLE
Can't encode interface of `RawExt`.

### ISSUE THREAD

**Issue by methane** [ugorji/go#48]
See https://gist.github.com/methane/bffc908568deb96c2a27

**Comment by ugorji** [comment]
Good catch. Oversight on my part. Thanks so much for seeing this and filing it.

The reflect.Value passed in on an encode is always dereferenced (never a pointer) by the time the encFnInfo methods get called. So the correct fix is to pass the ptr (if addressable) or a ptr to the value to EncodeRawExt.

I will submit a more correct fix in a few minutes.

Thanks.

**Comment by ugorji** [comment]
See https://gist.github.com/ugorji/5127e288f5ca2a76ef6b

I updated your gist to test out a few other scenarios.
