### ISSUE TITLE
Canonical encodings

### ISSUE THREAD

**Issue by heavenlyhash** [ugorji/go#56]
I need to do a "canonical" encoding in CBOR -- much as described in http://tools.ietf.org/html/rfc7049#section-3.9.  In other words, I need to make some calls to the encoder that when given the same inputs, have identical binary outputs.  (Though it's probably not relevant, in the bigger picture, this is for feeding into a cryptographic hash, so yes, the input->binaryoutput mapping has to be *identical* every time.)

How can I do this?

I think codec already mostly does the right thing with ints and so forth, but maps are a sticking point.  Here's what I considered so far:

- It looks like the default path accepts the random key ordering of golang map, so that's out.

- `cborEncDriver` has enough exported methods on it that I might be able to get the trick done by hand (and that'd be fine; since this is finicky work with byte layouts, it's fair if my code has to do fairly manual byte concatenations, as long as it's not totally re-copying everything down to the magic constants and int/type layouts)... except it (and a bunch of other important magic constants) are not exported, so I can't just initialize it.

- `fast-path.go.tmpl` seemed like it offered a glimmer of hope for a second, because it's *doing* the things I need to do... but it looks like that code only works from within the codec package (lo and behold it's using those unexported encoder drivers).

- ... Ah ha!  I can use `GenHelperEncoder` to get access to all the fun stuff.  It's documented as not for use, but...

Option 4 is the only thing I've found that's capable of doing what's needed to output a consistent/canonical form.  Is there anything I've missed that's a better way of addressing this?  Are there any code changes I could help PR that would make this better?

**Comment by ugorji** [comment]
Taking a step back, it seems that you want support for sorted encoding of mappings. Is that a fair summary of your request?

**Comment by heavenlyhash** [comment]
Yep!  That's the one thing I've hit in practice that was tricky for getting deterministic output.

I'd *almost* say that what I want is canonical cbor output, but with the interesting exception that I also need streams, which is technically a break from what the rfc suggests for canonical encoding.

I went ahead and made a prototype that does what I needed, so I'm going full steam ahead with using `codec` on that project (and it's fantastic!  Thank you for all this awesome work!), but I did end up using `GenHelperEncoder` to do so despite the may-change-without-notice warnings.  (We pin dependencies by commit hash in that project, so I'm not worried, and totally accept I might have to nontrivial refactors in the future. :) )  If you want to see the example of how that turned out, it's [here](https://github.com/polydawn/repeatr/blob/cd19926ceaf7343cfe898c653cf6747ec02b070e/lib/fshash/metadata.go#L79) and [here](https://github.com/polydawn/repeatr/blob/cd19926ceaf7343cfe898c653cf6747ec02b070e/lib/fshash/hash.go#L60).

It might also be nice to have a method for encoding maps that'll do keys in an order specified by a `[]string keys` (well, or just expose an interface like the `GenHelperEncoder` officially where map appends can be called in the desired order directly) -- this would be useful in a situation where someone is implementating an encoding for something that has to match an existing spec that's deterministic order but not sorted.

**Comment by ugorji** [comment]
K.

I have an upcoming change to support canonical encodings.

It works by configuring an option on the handle i.e. Canonical=true.

Canonical mode is ignored for code generation. It only works for the standard reflection-based runtime introspection. Also, there is a performance hit, as each key must be encoded out-of-band, then all key encodings compared, and then the key-values are encoded. 

The good part is that it fits in with the rest of the library, so is supported. 
Using "internal", "unsupported" APIs will prevent you from easy upgrade, so is highly discouraged. 

The change should be uploaded today. Let me know if this will work for you before I make the update.

Thanks.

**Comment by heavenlyhash** [comment]
The performance hit caveat makes sense.  Even with that, it'd definitely be great to have this in the supported APIs.

Do you think an explicit `MapAppend(k, v interface{})` is also exposable?  Maybe it's not the most general API, but I think it makes sense for most encoding formats I can think of, and it seems to make sense from the way the internals work right now (though I suppose what I wrote along those lines was cbor specific...).  And raising some sort of "unsupported" error an encoding format doesn't support user-chosen map orders seems totally reasonable.

**Comment by heavenlyhash** [comment]
This is awesome!  I look forward to using it in future protocols. :D
