### ISSUE TITLE
Doesn't encode []map[string]*mapval correctly

### ISSUE THREAD

**Issue by clbanning** [ugorji/go#57]
Needs to separate map k:v pairs with commas  - ',' - use case below w/o codecgen output.  To complete "go test" case run "codecgen -o codecdemo_codec.go codecdemo.go" first.

codecdemo.go:

package codecdemo

import (
	"github.com/ugorji/go/codec"
	"strconv"
	"time"
)

type MapVal struct {
	Name string
	Time time.Time
}

type Entry struct {
	Vals map[string]*MapVal
}

type Wrapper struct {
	Entries []*Entry
}

func Codecdemo() ([]byte, error) {
	w := new(Wrapper)
	w.Entries = make([]*Entry, 1)
	e := new(Entry)
	w.Entries[0] = e
	w.Entries[0].Vals = make(map[string]*MapVal, 0)

	for i := 0; i < 4; i++ {
		m := new(MapVal)
		m.Name = strconv.Itoa(i + 1)
		m.Time = time.Now()
		w.Entries[0].Vals[m.Name] = m
	}

	b := make([]byte, 0)
	h := new(codec.JsonHandle)
	enc := codec.NewEncoderBytes(&b, h)
	if err := enc.Encode(w); err != nil {
		return nil, err
	}

	return b, nil
}

codecdemo_test.go:

import (
	"encoding/json"
	"testing"
)

func TestCodecDemo(t *testing.T) {
	val, err := Codecdemo()
	if err != nil {
		t.Fatal(err)
	}

	m := new(Wrapper)
	if err = json.Unmarshal(val, m); err != nil {
		println("val:", string(val))
		t.Fatal(err)
	}

	println("val:", string(val))
}

**Comment by ugorji** [comment]
It's not clear what your issue is. 

I reproduced this, and it worked fine.

https://gist.github.com/ugorji/8bb851bf49cff1c3d4d9

**Comment by clbanning** [comment]
Does not work with codecgen code generation on a package.
