### ISSUE TITLE
Generator and new types (alias)

### ISSUE THREAD

**Issue by DAddYE** [ugorji/go#63]
Hi there,

I have something like this:

```go
type MessageStatus int32 

type Message struct {
    Body string
    Status MessageStatus
}
```

The generated code will do type conversion to MessageStatus to `int32` instead of `MessageStatus`. 

Error message will look like:

```
cannot use int32(r.DecodeInt(32)) (type int32) as type MessageStatus in assignment
```

**Comment by ugorji** [comment]
I don't understand your report.

Can you please create a file with a main method that I can run to reproduce the problem?

Thanks.

**Comment by DAddYE** [comment]
It's the same I posted:


foo.go
```go
package foo

type MessageStatus int32

type Message struct {
	Body   string
	Status MessageStatus
}
```

```sh
tmp $ codecgen -o foo_gen.go foo.go
```

generates fines. But if I build the generated file I get:

```
tmp $ go build
# _/private/tmp
./foo_gen.go:169: cannot use int32(r.DecodeInt(32)) (type int32) as type MessageStatus in assignment
./foo_gen.go:216: cannot use int32(r.DecodeInt(32)) (type int32) as type MessageStatus in assignment
```

**Comment by ugorji** [comment]
Thanks. I understand now and have reproduced it with your steps.

I will follow up soon.
