### ISSUE TITLE
"omitempty" fails on pointers to bools

### ISSUE THREAD

**Issue by teepark** [ugorji/go#67]
A struct field of type *bool which points to false is triggering the "omitempty" behavior even though it's not a nil pointer. This is not the zero value of the *bool type, so it shouldn't cause the field to be omitted (this is a trick to get "false" to show up in output, but still be able to leave the field out entirely).

**Comment by ugorji** [comment]
Please add a reproducer that I can run and test with.

**Comment by ugorji** [comment]
Fixed
