### ISSUE TITLE
Slow codec

### ISSUE THREAD

**Issue by fgrzadkowski** [ugorji/go#69]
I'm trying to improve (un)marshaling of Node type:
https://github.com/coreos/go-etcd/blob/master/etcd/response.go#L65

I generated codec file using ```codecgen -o values.generated.go -u response.go```. After fixing #68 manually I did some benchmarking:

```
package etcd

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/ugorji/go/codec"
)

func CreateTestNode() *Node {
	return &Node{
		Key:           strings.Repeat("a", 30),
		Value:         strings.Repeat("a", 2000),
		Nodes:         make([]*Node, 0),
		TTL:           123456789,
		ModifiedIndex: 123456,
		CreatedIndex:  123456,
	}
}

// BenchmarkEncodeJSON provides a baseline for regular JSON encode performance
func BenchmarkFasterEncodeJSON(b *testing.B) {
	node := CreateTestNode()
	for i := 0; i < 3000; i++ {
		node.Nodes = append(node.Nodes, CreateTestNode())
	}
	b.ResetTimer()

	var out []byte = make([]byte, 0, 10000000)
	var h codec.Handle = new(codec.JsonHandle)
	var enc *codec.Encoder = codec.NewEncoderBytes(&out, h)
	for i := 0; i < b.N; i++ {
		enc.Encode(node)
	}
}

// BenchmarkEncodeJSON provides a baseline for regular JSON encode performance
func BenchmarkEncodeJSON(b *testing.B) {
	node := CreateTestNode()
	for i := 0; i < 3000; i++ {
		node.Nodes = append(node.Nodes, CreateTestNode())
	}
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		json.Marshal(&node)
	}
}
```

Results:

```
$ go test -test.run=XXXXX -bench=EncodeJSON
PASS
BenchmarkFasterEncodeJSON	     100	  22638556 ns/op
BenchmarkEncodeJSON	     100	  22440881 ns/op
ok  	github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd	4.670s
```

It seems that this codec is slower than a regular json marshaller.

**Comment by ugorji** [comment]
Your 2 benchmark functions are doing 2 different things.

For stdlib encoding/json, you are encoding it each time into a new scratch buffer. 
For codec, you are first creating a 10MB array and then concatenating each iteration of the i...b.N to it. So your benchmark was really growing that 10MB array to about 500MB-1GB. 

For a more apples to apples benchmark, your benchmark for codec should look like this:

func BenchmarkFasterEncodeJSON(b *testing.B) {
    node := CreateTestNode()
    for i := 0; i < 3000; i++ {
        node.Nodes = append(node.Nodes, CreateTestNode())
    }  
    var h codec.Handle = new(codec.JsonHandle) // equivalent to what init() of encoding/json has done
    var out []byte =  make([]byte, 10000000)
    b.ResetTimer()
    for i := 0; i < b.N; i++ {
        out = out[:0] // truncate it, so it writes to same buffer
        codec.NewEncoderBytes(&out, h).Encode(node)
    }
}

Please try this and let me know what your results look like.

**Comment by fgrzadkowski** [comment]
Results:
```
$ go test -test.run=XXXXX -bench=JSON
PASS
BenchmarkFasterEncodeJSON	     100	  18419839 ns/op
BenchmarkEncodeJSON	      50	  22562542 ns/op
BenchmarkFasterDecodeJSON	      20	  60708058 ns/op
BenchmarkDecodeJSON	      10	 102479416 ns/op
ok  	github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd	5.597s
```

**Comment by ugorji** [comment]
Thanks.

From these results, codec takes 23% less time on encode, and 41% less time on decode.

I think we can close this.

**Comment by fgrzadkowski** [comment]
Thanks for looking into this!
