### ISSUE TITLE
Decoding a msgpack input with int keys to a defined type

### ISSUE THREAD

**Issue by kgrz** [ugorji/go#77]
I'm new to Go ( and statically typed languages in general ). I wrote a small script that would fetch information over a network from a server which serializes a hash(dict) using msgpack. This is the generic structure of the hash/dict:

```
{
  0: 8,
  1: <timestamp in milliseconds>,
  2: {
    "server_version" => <Version of the server>,
    "protocol_version" => <Version of message protocol used on the server>,
    "process_name" => <Name of the process>,
    "pwd" => <working directory of the app>,
    "pid" => <PID of the ruby process>,
    "object_trace_enabled" => <0 or 1>
  }
}
```

Notice that the first-level keys of the hash-map(or dict) are integers. I'm able to decode this input using the variable with signature: `var msg map[int]interface{}`. However, this results in the value with key `2` becoming an `interface{}` type which requires one more step to iterate or query using the keys. I wanted to use a custom type declaration to get a proper Go struct. I was trying to use this type of type declaration:

```go
type HandshakeResponse struct {
	EventType int     `codec:"0,omitempty"`
	Timestamp float64 `codec:"1,omitempty"`
	Payload   struct {
		ServerVersion          string `codec:"server_version"`
		ProtocolVersion        string `codec:"protocol_version"`
		ProcessName           string `codec:"process_name"`
		Pwd                           string `codec:"pwd"`
		Pid                             int    `codec:"pid"`
		ObjectTraceEnabled int    `codec:"object_trace_enabled"`
	} `codec:"2,omitempty"`
}
``` 

However, this doesn't work. I'm assuming that's because the `0`,`1`,`2` in the type declaration tags are `string`s in the type definition, but the keys from the msgpack data are `int`s. Here is an example that works fine:

(modified data from server):
```
{
  'event_type': 8,
  'timestamp': <timestamp in milliseconds>,
}
```

```go
type HandshakeResponse struct {
	EventType string     `codec:"event_type,omitempty"`
	Timestamp float64 `codec:"timestamp,omitempty"`
	Payload   struct {
		ServerVersion          string `codec:"server_version"`
		ProtocolVersion        string `codec:"protocol_version"`
		ProcessName           string `codec:"process_name"`
		Pwd                           string `codec:"pwd"`
		Pid                             int    `codec:"pid"`
		ObjectTraceEnabled int    `codec:"object_trace_enabled"`
	} `codec:"payload,omitempty"`

}
```

The question is, is there any way I can represent the keys in my type declaration as `int`s? I'm not yet confident enough to read through the source code and make sense of this. I've gone through the docs and there was a mention of extensions. Is this what I'm supposed to use? Or is there a simpler way that I've missed?

PS: This won't be a problem with JSON since a valid JSON document won't ever exist with a numerical key type. But I'm assuming that won't be a common consideration for msgpack which doesn't specify such constraints.

**Comment by ugorji** [comment]
Unfortunately, This is a limitation of Go and structs and the serialization design.

You cannot do what you are trying to do.

You either serialize as a struct which mapsstring key to custom type, or you serialize as a typed map, like map[int]interface{}. You are already aware of both options.

**Comment by ugorji** [comment]
The other option is to serialize as an array, not a hash. A struct can be deserialuzed from an array e.g. {8, milliseconds, {...} }
