### ISSUE TITLE
Constant int overflows

### ISSUE THREAD

**Issue by zvbuhl** [ugorji/go#78]
```sh
go-fuzz-build $PACKAGE
failed to execute go build: exit status 2
# github.com/ugorji/go/codec
/tmp/go-fuzz-build014437353/src/github.com/ugorji/go/codec/cbor.go:133: constant 18446744073709551615 overflows int
/tmp/go-fuzz-build014437353/src/github.com/ugorji/go/codec/json.go:454: constant 18446744073709551615 overflows int
/tmp/go-fuzz-build014437353/src/github.com/ugorji/go/codec/json.go:1127: constant 18446744073709551615 overflows int
/tmp/go-fuzz-build014437353/src/github.com/ugorji/go/codec/simple.go:115: constant 18446744073709551615 overflows int```

**Comment by ugorji** [comment]
What is the bug here? Please verify its a bug and not an issue with your fuzz tool or a false negative.

**Comment by zvbuhl** [comment]
I'll create a simple test case.

**Comment by zvbuhl** [comment]
Alright, so this is caused by the interaction of ugorji/go/codec and go-fuzz, due to the fact that constants in Go default to int, even if they are too large to fit into an int (!) (the issue arises since go-fuzz instruments each source line with a call to a function which takes an interface, and it's impossible in Go to pass a large constant to a function taking an interface{}, c.f. http://play.golang.org/p/ZHIqgtuwez).

As far as go-fuzz goes, there appears to be no way for it to detect that the constants are large (go/ast doesn't seem to provide that information).

So, the error isn't in ugorji/go/codec, and it's not in go-fuzz.

The good news is that I found the four lines in question, and it turns out that the references to math.MaxUint64 are no-ops. I'll be submitting a pull request in a few minutes.

**Comment by ugorji** [comment]
This is a go-fuzz false negative. I am now closing the issue.
