### ISSUE TITLE
JSON struct tag is not being picked up

### ISSUE THREAD

**Issue by drewwells** [ugorji/go#80]
I am still working on how to reproduce this problem in an isolated case. Thought I would post in case you had ideas. The struct is nested a couple layers deep in `interface{}`s. We always have a json struct on it, but codec encoding fails to read the json struct tag. Adding a `codec` struct tag resolves the problem. 

As an example, this struct does not get encoded properly
```
type A struct {
  TwoWord string `json:"two_word"`
}
```

but this one does
```
type A struct {
  TwoWord string `json:"two_word" codec:"two_word"`
}
```

**Comment by drewwells** [comment]
My package was 16months out of date ><

**Comment by ugorji** [comment]
@drewwells json tag is now also supported, to make transition easier for encoding/json users
