### ISSUE TITLE
Question about 'codecgen'

### ISSUE THREAD

**Issue by diegobernardes** [ugorji/go#81]
Before anything, thx for the project, its amazing :smile: 

About the codecgen, what its real benefit of using it? Doing some benchmarks it has the same performance of using the package direct and its almost the same syntax of using the library direct.

Other question is, to decode my JSON i had to create a extension. When i try to decode direct in the library, there is no problem, it use my extension, but when i execute 'codecgen' it dont use the extension and because of this, it gives me error.
The error most of the time is in 'time.Duration' , some times the value is a int and some times a float, this is why i did the extension.

About performance, i don't know why, but the performance is very slow compared to java, im decoding a 3.5mb [HAR](http://www.softwareishard.com/blog/har-12-spec/). Java decode in +/-19ms and golang in +/-40ms.
Did someone already compared the speed to java?

Bad times ahead if this is the max speed :/ i need to decode terabytes of data per day and need all the speed available.
The half of speed can result in hours more to process the data. I need to parse 500k+ of this files per day.

This is the project that im doing: https://github.com/diegobernardes/har/tree/feature/core

**Comment by ugorji** [comment]
The syntax should be the same.

See performance numbers when I run our benchmarks, using our large test struct with an extra level of embedding itself. It shows that encoding is about 12X faster, and decoding is 2X faster.

```
ugorji@ugorji-xps15:~/depot/repo/src/ugorji.net/codec$ ./bench.sh -igp -d 2 -t 2000ms 

Benchmark__Msgpack____Encode 	    5000	    495341 ns/op	   24192 B/op	     130 allocs/op
Benchmark__Msgpack____Decode 	    1000	   2811260 ns/op	   32496 B/op	     794 allocs/op
Benchmark__Cbor_______Encode 	    5000	    494930 ns/op	   24192 B/op	     130 allocs/op
Benchmark__Cbor_______Decode 	    1000	   2800995 ns/op	   32496 B/op	     794 allocs/op
Benchmark__Json_______Encode 	    5000	    519254 ns/op	   24272 B/op	     130 allocs/op
Benchmark__Json_______Decode 	    1000	   3820743 ns/op	   38944 B/op	    1019 allocs/op

=======================

ugorji@ugorji-xps15:~/depot/repo/src/ugorji.net/codec$ ./bench.sh -uigpc -d 2 -t 2000ms 

Benchmark__Msgpack____Encode 	  100000	     35295 ns/op	     272 B/op	       3 allocs/op
Benchmark__Msgpack____Decode 	    2000	   1453805 ns/op	   24816 B/op	     437 allocs/op
Benchmark__Cbor_______Encode 	  100000	     35617 ns/op	     272 B/op	       3 allocs/op
Benchmark__Cbor_______Decode 	    2000	   1451437 ns/op	   24816 B/op	     437 allocs/op
Benchmark__Json_______Encode 	   50000	     69135 ns/op	     352 B/op	       3 allocs/op
Benchmark__Json_______Decode 	    2000	   2232132 ns/op	   30720 B/op	     632 allocs/op
```

Regarding go vs java, go's machine code and optimizer and GC are not as performant as java's (yet). Also, go's library may do more than java's (including omitempty, etc); these features at runtime will have a cost. I don't know enough about the java library you used, or your benchmarks, to do a fair explanation.

**Comment by diegobernardes** [comment]
Thanks!
