### ISSUE TITLE
extract sub packages

### ISSUE THREAD

**Issue by jbenet** [ugorji/go#83]
it is unwieldy to have to include the whole package to get -- say -- cbor coding. with the vendoring.

It would be much nicer if there was a core `codec` package with the interfaces, and then:

```
codec/json
codec/cbor
...
```

**Comment by ugorji** [comment]
It can't work that way. 

If we use packages like codec/json and codec/cbor, then a lot more of the shared infrastructure has to be exported, and corresponding methods in json and cbor must be exported. This dramatically increases the 
public surface area, making changes much harder to manage.
