### ISSUE TITLE
cbor: test against cbor/test-vectors

### ISSUE THREAD

**Issue by jbenet** [ugorji/go#85]
https://github.com/cbor/test-vectors/blob/master/appendix_a.json

**Comment by ugorji** [comment]
These tests already exist as https://github.com/ugorji/go/blob/master/codec/test-cbor-goldens.json
and are tested by TestCborGoldens in https://github.com/ugorji/go/blob/master/codec/cbor_test.go .

Did you check?

**Comment by jbenet** [comment]
> These tests already exist

great! 

you may want to note it in the tests, including the repo the data came from and how to update it if it changes. maybe this is there and i missed it -- the codebase is not a paragon of clarity.

> Did you check?

- I did. it was not obvious. not even close.
- maybe if you split your code up, it would be more obvious. golang is a language meant to make it easy to split out packages into small units. it makes it easier for other people to work with you and contribute to the code. but suit yourself, it's your code/project :smile:
