### ISSUE TITLE
sql.Null* structs with different output

### ISSUE THREAD

**Issue by SchumacherFM** [ugorji/go#92]
First, I thank you for the great project!

Given the following situation:

```
type NullString struct {
	sql.NullString
}
var nullString = []byte("null")

// MarshalJSON correctly serializes a NullString to JSON
func (n *NullString) MarshalJSON() ([]byte, error) {
	if n.Valid {
		j, e := json.Marshal(n.String)
		return j, e
	}
	return nullString, nil
}
```

NullString satisfies the encoding/json interface for custom marshaling. The json output of a NullString type would not be:

```
"Code":{"String":"de","Valid":true}
```

it will be 

```
"Code":"de"
```

Is there a possibility to achieve the same with an additional interface on the type NullString with your encoder/decoder? 😀

**Comment by SchumacherFM** [comment]
Sorry ... should have better read the doc :-)

```
type Selfer interface {
	CodecEncodeSelf(*Encoder)
	CodecDecodeSelf(*Decoder)
}
```

**Comment by ugorji** [comment]
@SchumacherFM codec now supports (M|Unm)arshalJSON when using the JSON Handle. This may help make your transition easier.

**Comment by SchumacherFM** [comment]
Cool! Thanks! I've implemented your pkg here: https://github.com/corestoreio/csfw/blob/master/codegen%2FtableToStruct%2Fcodecgen%2Fgen.go

I'm afraid that I have to include your files because you didn't provide a public API.
