### ISSUE TITLE
cbor encoding fails to produce equal buffers (with canonical = true)?

### ISSUE THREAD

**Issue by jbenet** [ugorji/go#93]
I have a few cases where cbor encoding fails to produce the exact same output with `h.Canonical = true`. 

Please see https://github.com/jbenet/test-ugorji-cbor

Setup:

- some test maps
- a roundtrip function that compares the two cbor bufs in a roundtrip:

    ```
    go map -> cbor buf 1 -> go map 2 -> cbor buf 2
    bytes.Equal(cbor buf 1, cbor buf 2)
    ```
- buffers not equal, even though `h.Canonical = true`
- deep equals on maps fails too, not sure why (probably has to do with map types stuff)

Output: 
```
> go test
--- FAIL: TestRoundtripBasic (0.00s)
    rt_test.go:42: marshalled values not equal
    rt_test.go:43: [163 97 97 1 97 98 101 104 101 108 108 111 97 99 164 99 99 47 97 1 99 99 47 98 101 119 111 114 108 100 99 99 47 99 132 1 2 3 4 99 99 47 100 166 101 99 47 100 47 97 120 32 102 100 105 115 97 106 102 111 105 100 115 97 106 102 111 112 100 106 115 97 111 112 102 106 100 115 97 112 111 102 100 97 101 99 47 100 47 98 120 56 102 100 115 97 102 106 100 112 111 115 97 107 102 111 100 112 115 97 107 102 111 112 100 115 97 107 102 112 111 100 115 97 107 102 112 111 100 107 115 97 111 112 102 107 100 115 111 112 97 102 107 100 111 112 115 97 101 99 47 100 47 99 120 66 112 111 105 114 48 50 32 32 105 114 51 48 113 105 102 52 112 48 51 113 105 114 48 112 111 103 106 102 112 111 97 101 114 102 103 106 112 32 111 102 107 101 91 112 97 100 102 107 91 101 119 97 112 102 32 107 100 112 91 97 102 101 112 91 97 119 101 99 47 100 47 100 120 61 102 100 115 111 112 97 102 107 100 91 115 97 32 102 45 51 50 113 111 114 45 61 52 113 101 111 102 32 45 97 102 111 45 101 114 102 111 32 114 45 101 97 102 111 32 52 101 45 32 32 111 32 114 52 45 113 119 111 32 97 103 101 99 47 100 47 101 120 76 107 102 101 112 91 97 32 115 102 107 114 48 91 112 97 102 91 97 32 102 111 101 45 91 119 113 32 32 101 119 112 102 97 111 45 113 32 114 111 51 45 113 32 114 111 45 52 113 111 102 52 45 113 111 114 32 51 45 101 32 111 114 102 107 114 111 112 122 106 98 118 111 105 115 100 98 101 99 47 100 47 102 96]
    rt_test.go:44: [163 97 97 1 97 98 101 104 101 108 108 111 97 99 164 99 99 47 100 166 101 99 47 100 47 98 120 56 102 100 115 97 102 106 100 112 111 115 97 107 102 111 100 112 115 97 107 102 111 112 100 115 97 107 102 112 111 100 115 97 107 102 112 111 100 107 115 97 111 112 102 107 100 115 111 112 97 102 107 100 111 112 115 97 101 99 47 100 47 99 120 66 112 111 105 114 48 50 32 32 105 114 51 48 113 105 102 52 112 48 51 113 105 114 48 112 111 103 106 102 112 111 97 101 114 102 103 106 112 32 111 102 107 101 91 112 97 100 102 107 91 101 119 97 112 102 32 107 100 112 91 97 102 101 112 91 97 119 101 99 47 100 47 100 120 61 102 100 115 111 112 97 102 107 100 91 115 97 32 102 45 51 50 113 111 114 45 61 52 113 101 111 102 32 45 97 102 111 45 101 114 102 111 32 114 45 101 97 102 111 32 52 101 45 32 32 111 32 114 52 45 113 119 111 32 97 103 101 99 47 100 47 101 120 76 107 102 101 112 91 97 32 115 102 107 114 48 91 112 97 102 91 97 32 102 111 101 45 91 119 113 32 32 101 119 112 102 97 111 45 113 32 114 111 51 45 113 32 114 111 45 52 113 111 102 52 45 113 111 114 32 51 45 101 32 111 114 102 107 114 111 112 122 106 98 118 111 105 115 100 98 101 99 47 100 47 102 96 101 99 47 100 47 97 120 32 102 100 105 115 97 106 102 111 105 100 115 97 106 102 111 112 100 106 115 97 111 112 102 106 100 115 97 112 111 102 100 97 99 99 47 97 1 99 99 47 98 101 119 111 114 108 100 99 99 47 99 132 1 2 3 4]
FAIL
exit status 1
FAIL    _/tmp/testcanonical 0.012s
```

any help much appreciated, as we'd like to use cbor but need output buffers to be equal for cryptographic protocols to work at all.

**Comment by ugorji** [comment]
Your test doesn't just test canonical.

To test canonical, it is sufficient to encode a value multiple times, and ensure you get the same sequence of bytes.

What you are testing, is that if you encode a value to a stream of bytes, and you decode the stream to a nil interface{}, you will get the exact same value. That is not a guaranteed thing. For example, you could encode an int to a stream, and decode it as a uint. If you encode it again, it may be different. Also, you could encode a string to a sequence of bytes, and decode it as a []byte, etc. 

(I'm busy now, so giving you a rushed response, but the sentiment is true, even if the examples are not fully thought out).

**Comment by jbenet** [comment]
### (1)  what you say seems NOT to apply here. the encoded values contain _the exact same bytes_, just out of order. 

look at the buffers again:

```
 rt_test.go:43: [163 97 97 1 97 98 101 104 101 108 108 111 97 99 164 99 99 47 97 1 99 99 47 98 101 119 111 114 108 100 99 99 47 99 132 1 2 3 4 99 99 47 100 166 101 99 47 100 47 97 120 32 102 100 105 115 97 106 102 111 105 100 115 97 106 102 111 112 100 106 115 97 111 112 102 106 100 115 97 112 111 102 100 97 101 99 47 100 47 98 120 56 102 100 115 97 102 106 100 112 111 115 97 107 102 111 100 112 115 97 107 102 111 112 100 115 97 107 102 112 111 100 115 97 107 102 112 111 100 107 115 97 111 112 102 107 100 115 111 112 97 102 107 100 111 112 115 97 101 99 47 100 47 99 120 66 112 111 105 114 48 50 32 32 105 114 51 48 113 105 102 52 112 48 51 113 105 114 48 112 111 103 106 102 112 111 97 101 114 102 103 106 112 32 111 102 107 101 91 112 97 100 102 107 91 101 119 97 112 102 32 107 100 112 91 97 102 101 112 91 97 119 101 99 47 100 47 100 120 61 102 100 115 111 112 97 102 107 100 91 115 97 32 102 45 51 50 113 111 114 45 61 52 113 101 111 102 32 45 97 102 111 45 101 114 102 111 32 114 45 101 97 102 111 32 52 101 45 32 32 111 32 114 52 45 113 119 111 32 97 103 101 99 47 100 47 101 120 76 107 102 101 112 91 97 32 115 102 107 114 48 91 112 97 102 91 97 32 102 111 101 45 91 119 113 32 32 101 119 112 102 97 111 45 113 32 114 111 51 45 113 32 114 111 45 52 113 111 102 52 45 113 111 114 32 51 45 101 32 111 114 102 107 114 111 112 122 106 98 118 111 105 115 100 98 101 99 47 100 47 102 96]
    rt_test.go:44: [163 97 97 1 97 98 101 104 101 108 108 111 97 99 164 99 99 47 100 166 101 99 47 100 47 98 120 56 102 100 115 97 102 106 100 112 111 115 97 107 102 111 100 112 115 97 107 102 111 112 100 115 97 107 102 112 111 100 115 97 107 102 112 111 100 107 115 97 111 112 102 107 100 115 111 112 97 102 107 100 111 112 115 97 101 99 47 100 47 99 120 66 112 111 105 114 48 50 32 32 105 114 51 48 113 105 102 52 112 48 51 113 105 114 48 112 111 103 106 102 112 111 97 101 114 102 103 106 112 32 111 102 107 101 91 112 97 100 102 107 91 101 119 97 112 102 32 107 100 112 91 97 102 101 112 91 97 119 101 99 47 100 47 100 120 61 102 100 115 111 112 97 102 107 100 91 115 97 32 102 45 51 50 113 111 114 45 61 52 113 101 111 102 32 45 97 102 111 45 101 114 102 111 32 114 45 101 97 102 111 32 52 101 45 32 32 111 32 114 52 45 113 119 111 32 97 103 101 99 47 100 47 101 120 76 107 102 101 112 91 97 32 115 102 107 114 48 91 112 97 102 91 97 32 102 111 101 45 91 119 113 32 32 101 119 112 102 97 111 45 113 32 114 111 51 45 113 32 114 111 45 52 113 111 102 52 45 113 111 114 32 51 45 101 32 111 114 102 107 114 111 112 122 106 98 118 111 105 115 100 98 101 99 47 100 47 102 96 101 99 47 100 47 97 120 32 102 100 105 115 97 106 102 111 105 100 115 97 106 102 111 112 100 106 115 97 111 112 102 106 100 115 97 112 111 102 100 97 99 99 47 97 1 99 99 47 98 101 119 111 114 108 100 99 99 47 99 132 1 2 3 4]
```

Here, look at this:

![](http://gateway.ipfs.io/ipfs/QmS2FsgaFeLoGGX1LeBXnJL1NRe7mjrtPbd3ve87MTzWbQ/cap.png)

AFAICT (i have not checked every single byte) this is not _changed_ bytes. it's _relocated_ bytes. 

### (2) on ints being encoded and decided _differently_ by the same modules

Then our version of canonical here is very weak! the CBOR spec specifically points out the following (bold mine):

> If a protocol considers "canonical" to mean that two encoder
> implementations starting with the same input data will produce the
> same CBOR output, the following four rules would suffice:
> 
> -  Integers must be as small as possible.
> 
>    *  0 to 23 and -1 to -24 must be expressed in the same byte as the
>       major type;
> 
>    *  24 to 255 and -25 to -256 must be expressed only with an
>       additional uint8_t;
> 
>    *  256 to 65535 and -257 to -65536 must be expressed only with an
>       additional uint16_t;
> 
>    *  65536 to 4294967295 and -65537 to -4294967296 must be expressed
>       only with an additional uint32_t.
> 
> -  The expression of lengths in major types 2 through 5 must be as
>    short as possible.  The rules for these lengths follow the above
>    rule for integers.
> 
> -  The keys in every map must be sorted lowest value to highest.
>    Sorting is performed on the bytes of the representation of the key
>    data items without paying attention to the 3/5 bit splitting for
>    major types.  (Note that this rule allows maps that have keys of
>    different types, even though that is probably a bad practice that
>    could lead to errors in some canonicalization implementations.)
>    The sorting rules are:
> 
>    *  If two keys have different lengths, the shorter one sorts
>       earlier;
> 
>    *  If two keys have the same length, the one with the lower value
>       in (byte-wise) lexical order sorts earlier.
> 
> -  Indefinite-length items must be made into definite-length items.
>
> --- From http://tools.ietf.org/html/rfc7049#section-3.9

This takes care of the claim:

> For example, you could encode an int to a stream, and decode it as a uint. If you encode it again, it may be different.

which would be a far from canonical. As far as wire protocols (in particular, cryptographically secure protocols) are concerned, canonical tends to mean _byte-for-byte equal_. Though the authors of the cbor spec do not _require_ a canonical definition as extreme, they do define a set of rules to achieve it. I think the utility of a serialization module which _cannot reliably produce the same output_ is strongly diminished (deserializing to an `interface{}` or not).


### (3) Please do not close issues until opener has marked them resolved. 

Closing an issue before the issue filer has acknowledged resolution is liable to be incorrect, and is (frankly speaking) rude open-source manners. Nobody is infallible.

**Comment by ugorji** [comment]
Dude! Relax. Your #3 was totally unnecessary, and frankly deserves an apology!

**Comment by jbenet** [comment]
> Dude! Relax. Your #3 was totally unnecessary, and frankly deserves an apology!

@ugorji i feel the same way about your dismissing the issue and closing it :smile: sends the message:  "you're doing it wrong, go away". it's like tagging something `#wontfix`.  Frankly speaking, doing that -- after I dug into this and took the time to make a test case to reproduce the problem -- comes off rude.

**Comment by jbenet** [comment]
(thought i had posted this, but not seeing it on github, sorry for double port)

Other standards that build on the base CBOR standard -- like https://tools.ietf.org/html/draft-ietf-cose-msg-03 -- call for the strictest notion of canonical (achieving equal byte-for-byte representations). See https://tools.ietf.org/html/draft-ietf-cose-msg-03#section-14 -- (this is a standard coming from the [cose](http://datatracker.ietf.org/wg/cose/documents/) group, which needs the strict definition for the same reason we do: cryptographic protocols on cbor datastructures.
