### ISSUE TITLE
Generated code doesn't compile due to equal package names

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#94]
While generating code for our Kubernetes structures:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go
 I got a code that doesn't compile.

 The issue is that your code includes the two following imports:
- "k8s.io/kubernetes/pkg/runtime"
- "reflect"
 and there is name collision. You should probably add aliases for package imports where necessary.

**Comment by ugorji** [comment]
Can you please provide more context, and help me do some debugging, so I can do a fix quicker.

It helps if you provide:
- a small reproducer
- command line to run it
- error output
- analysis of the bug based on error, etc (if you have it)

This allows me get to reproduce and fix quicker. If not, the bug stays long on the github with no movement.

**Comment by wojtek-t** [comment]
I was generating conversions for this file:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go

The code that is produced doesn't compile because it has the following imports:
import (
	"errors"
	"fmt"
	codec1978 "github.com/ugorji/go/codec"
	"k8s.io/kubernetes/pkg/api/resource"
	"k8s.io/kubernetes/pkg/fields"
	"k8s.io/kubernetes/pkg/labels"
	"k8s.io/kubernetes/pkg/runtime"
	"k8s.io/kubernetes/pkg/types"
	"k8s.io/kubernetes/pkg/util"
	"reflect"
	"runtime"
	"speter.net/go/exp/math/dec/inf"
	"time"
)

The problematic ones are:
- "k8s.io/kubernetes/pkg/runtime"
- "runtime"
 because they generate naming collision (you refer to both of the via runtime.<class-name>).
 You should probably fix that by giving an alias to one of them, e.g.:

import(
 ...
 pkgruntime "k8s.io/kubernetes/pkg/runtime"
 ...
)

and the use pkgruntime.<class-name> instead of runtime.<class-name>

**Comment by ugorji** [comment]
Ah. Got it. Thanks.
