### ISSUE TITLE
"reflect.Value.Addr of unaddressable value" error while marshaling 

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#95]
When I was trying to use Ugorij for Kubernetes:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go
I received the following error: "reflect.Value.Addr of unaddressable value"

 How to reproduce it:
- I used the following code:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:use_ugorij#diff-a880abe356116a717967d2246a1ffc36R29
- This diff also contains a file that was generated for our structures.

 Please let me know if you need more information on reproducing it

**Comment by ugorji** [comment]
Can you please provide more context, and help me do some debugging, so I can do a fix quicker.

It helps if you provide:

- a small reproducer (preferably a single file e.g. bug95.go)
- command line to run it (preferably runnable via a "go run bug95.go)
- error output (so I can compare against your error when I run it)
- analysis of the bug based on error, etc (any initial analysis you have)

Sending me a link to the core code, and a diff, requires that I parse it for the core issue. And that is probably something you have already done. The cognitive overhead means I punt on following up on the bug till I have time, and there are no guarantees then. With a quick reproducer, the engineer in me quickly reproduces and understands the problem and wants to solve it ASAP.

**Comment by wojtek-t** [comment]
Sorry - I didn't do much debugging and I don't understand what is happening there.
And I don't have anything more than that diff.

**Comment by ugorji** [comment]
I don't know where to start, and I don't want to setup and run kubernetes to reproduce a problem, and start peeling away the onion. I looked at the diff, and was spinning wheels trying to understand what I was looking at, and looking for.

I will need you to do some more work to isolate a reproducer. 

Some things that could help:
- use MustEncode/MustDecode. These will show a panic stacktrace for where the error occurred, so you can debug easier

**Comment by ugorji** [comment]
I think the issue might be that you reference util.Time in your types. 

However, util.Time is not a encoding.(Binary|Text)(M|Unm)arshaler . Instead, you implement json.(M|Unm)arshaler. This interface is the legacy one, and is not supported outside the encoding/json package.

I still don't know if that is you real issue, but you will have to do more debugging and sending more error reports, as I could not reproduce your error message, even after getting kubernetes and running a shorter version of your usecase.

Please close the issue and re-open it when you have more information. If I don't hear from you in a couple of days, I will close it.

Code I used to test:

```
//+build ignore

package main

import (
	"io/ioutil"
	"log"
	"os"
	"reflect"

	"k8s.io/kubernetes/pkg/api"
	"github.com/ugorji/go/codec"
)

func main() {
	data, err := ioutil.ReadFile(os.Args[1]) // "node_example.json"
	if err != nil {
		log.Fatalf("read error: %v", err)
	}
	var node1, node2 api.Node
	var data2 []byte
	h := new(codec.JsonHandle)
	codec.NewDecoderBytes(data, h).MustDecode(&node1)
	codec.NewEncoderBytes(&data2, h).MustEncode(&node1)
	codec.NewDecoderBytes(data2, h).MustDecode(&node2)
	if !reflect.DeepEqual(&node1, &node2) {
		log.Fatalf("equal error: %v, %v", node1, node2)
	}
}
```

**Comment by ugorji** [comment]
@wojtek-t ping

**Comment by wojtek-t** [comment]
@ugorji - sorry I didn't have time to look into it today - I will look early next week. Please just leave it open.

**Comment by ugorji** [comment]
@wojtek-t ok

**Comment by ugorji** [comment]
Hi,

I updated codec and codecgen to now handle your requirements, including:

- support for (Unm|M)arshalJSON in both reflection-based and generated code

Please test it out and let me know how it works for you.

**Comment by wojtek-t** [comment]
@ugorji - thanks a lot for looking into it!

I've just updated the dependency locally and unfortunately it didn't help :(

I'm still using the same code to check it:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:use_ugorij

And it fails in the "Marshal" phase (I didn't even get to "Unmarshal"):

BenchmarkNodeMarshaling-12	--- FAIL: BenchmarkNodeMarshaling-12
	conversion_test.go:44: error: reflect.Value.Addr of unaddressable value

**Comment by ugorji** [comment]
@wojtek-t - I cannot recreate the problem you're having. 

I am testing with the code I referenced above in #issuecomment-138951691, which should isolate the problem if any exist. However, I cannot reproduce the problem. I did the following:

```
go get -u github.com/kubernetes/kubernetes/pkg/api
cd __PATH_TO_api
codecgen -o types.generated.go types.go
# github_95.go is the file in #issuecomment-138951691
go run github_95.go __PATH_TO_node_examples.go
```

And I got no errors.

Please try this out, and see if you get any errors. If you don't, then the problem is not with codec but is environmental or otherwise, and I cannot help you out there. I am not familiar with Godep, Kubernetes, or the rest of the Kubernetes setup. 

Also, please use MustEncode/MustDecode, so you can see the stacktrace where the error happens and that could help us diagnose the issue you are having, and align it to current source code for example.

I look forward to an update very soon. 

Thanks.

P.S. I even added a 

```
log.Printf("node1: %#v\n", node1)
```

and I get a nice printout of the node:

```
node1: api.Node{TypeMeta:api.TypeMeta{Kind:"Node", APIVersion:"v1"}, ObjectMeta:api.ObjectMeta{Name:"e2e-test-wojtekt-minion-etd6", GenerateName:"", Namespace:"", SelfLink:"/api/v1/nodes/e2e-test-wojtekt-minion-etd6", UID:"a7e89222-e8e5-11e4-8fde-42010af09327", ResourceVersion:"379", Generation:0, CreationTimestamp:util.Time{Time:time.Time{sec:63565300179, nsec:0, loc:(*time.Location)(0x1086880)}}, DeletionTimestamp:(*util.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Spec:api.NodeSpec{PodCIDR:"", ExternalID:"15488322946290398375", ProviderID:"", Unschedulable:false}, Status:api.NodeStatus{Capacity:api.ResourceList{"cpu":resource.Quantity{Amount:1.000, Format:"DecimalSI"}, "memory":resource.Quantity{Amount:1787035648.000, Format:"BinarySI"}}, Phase:"", Conditions:[]api.NodeCondition{api.NodeCondition{Type:"Ready", Status:"True", LastHeartbeatTime:util.Time{Time:time.Time{sec:63565300697, nsec:0, loc:(*time.Location)(0x1086880)}}, LastTransitionTime:util.Time{Time:time.Time{sec:63565300192, nsec:0, loc:(*time.Location)(0x1086880)}}, Reason:"kubelet is posting ready status", Message:""}}, Addresses:[]api.NodeAddress{api.NodeAddress{Type:"ExternalIP", Address:"104.197.49.213"}, api.NodeAddress{Type:"LegacyHostIP", Address:"104.197.20.11"}}, NodeInfo:api.NodeSystemInfo{MachineID:"", SystemUUID:"D59FA3FA-7B5B-7287-5E1A-1D79F13CB577", BootID:"44a832f3-8cfb-4de5-b7d2-d66030b6cd95", KernelVersion:"3.16.0-0.bpo.4-amd64", OsImage:"Debian GNU/Linux 7 (wheezy)", ContainerRuntimeVersion:"docker://1.5.0", KubeletVersion:"v0.15.0-484-g0c8ee980d705a3-dirty", KubeProxyVersion:"v0.15.0-484-g0c8ee980d705a3-dirty"}}}
```




where github_95.go is the file you had
after I successfully go-generated types.generated.go. I need to understand if this is a UserError, or a bug in the code. 

To help, I need you to 

Can you test with

**Comment by wojtek-t** [comment]
@ugorji - thanks I will take a look and let you know

**Comment by wojtek-t** [comment]
@ugorji - this was my bug (I was missing "&" in one place).
This problem seems to be fixed now.

Thanks a lot for the fixes!

**Comment by ugorji** [comment]
@wojtek-t Thanks for the update. 

However, I would like to understand initial problem, and see if there is something we could do in that situation. Even if it's not a pointer (ie no &), things should still work. Can you please tell me where the & was missing, preferably by changing the small reproducer I have, or something, so I can determine if/whether something should be done in the codebase to mitigate it.

Also, consider doing codecgen with a -u flag . That just helps prevent a lot of the constant []byte-to-string conversions that end up costing a lot of allocation, which is one of the biggest performance drain.

**Comment by wojtek-t** [comment]
So the issues was that I had:
     var result api.Node
     codec.NewEncoderBytes(&data, new(codec.JsonHandle)).Encode(node)
instead of
     codec.NewEncoderBytes(&data, new(codec.JsonHandle)).Encode(&node)

>
Also, consider doing codecgen with a -u flag . That just helps prevent a lot of the constant []byte-to-string conversions that end up costing a lot of allocation, which is one of the biggest performance drain.

Thanks - will take a look later (it seems that are still some issues and I'm trying to understand them).

**Comment by ugorji** [comment]
Hmm. That shouldn't matter i.e. encoding a Value Object or a pointer to it should be functionally equivalent. I just tried it out on my reproducer. I think the issue may be elsewhere. 

Feel free to post stuff in here to see if I could help you figure it out sooner.

**Comment by wojtek-t** [comment]
Thanks - will open a new issue when I have relatively easy way to reproduce.
