### ISSUE TITLE
Decoding of maps should accept bin objects as keys.

### ISSUE THREAD

**Issue by alesjaure** [ugorji/go#96]
When decoding the following byte stream, the decoder crashes:

  82 //fixmap2
    C407 //bin    --Decoding ERROR HERE
	  50524F46494C45 PROFILE
    C403
	 312E30
....
The binary object is not accepted as key for the map, but according to msgpack doc this should be fine. I wonder if this limitation in the library is related to the known golang limitation that arrays and slices cannot be key types in a map. Is there anyway to workaround this?

**Comment by ugorji** [comment]
Can you please prepare this as a reproducer that I can easily run? i.e. provide a go file, and code to run it, and error output.

Thanks.
