### ISSUE TITLE
Kubernetes util.IntOrString doesn't work correctly with codec.

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#97]
Again this is related to Kubernetes code.
This is related to our dedicated util.IntOrString types.

The following json file doesn't parse correctly:

{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"name":"redis-master"},"name":"redis-master"},"spec":{"ports":[{"port":6379,"targetPort":6379}],"selector":{"name":"redis-master"}}}

This json is parsed from the following yaml file:
https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/redis-master-service.yaml

Definition of the types is in:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go

The problem is explicitly related to "targetPort" field. The targetPort field is of type "util.IntOrString".
The Marshal/UnMarshal functions are explicitly defined in our code in this file:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/util.go

Please let me know what other information I can give you to simplify debugging.

**Comment by wojtek-t** [comment]
@ugorji

**Comment by ugorji** [comment]
Thanks @wojtek-t 

Can you please write some code (like what I did for github_95.go), and command line to run it, and what output you got, and what you expected. 

This way, I know exactly what the error is, and I don't have to fish for it. I can reproduce the exact error you get, and fix.

Thanks.

**Comment by wojtek-t** [comment]
Sure - will try to do it

**Comment by wojtek-t** [comment]
It seems that you can use ~your code from the previous issue:
https://github.com/ugorji/go/issues/95#issuecomment-138951691

The difference is that, you just read the following file instead:
https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/redis-master-service.yaml

and add the following lines after reading the file:
json, err := yaml.ToJSON(data)
if err != nil {
  panic("unexpected")
}
data = json

**Comment by ugorji** [comment]
I just used the code I have, and I replaced node_example.json with your json file above (saving it as github_issue.json). I didn't get any error. The only "error" was that *time.Location for CreationTimeStamp changed from nil, to probably time.UTC, and that's a result of the util.Time Marshal/Unmarshal. 

I still can't reproduce the error. Which is why I need you to reproduce it, and type the error message you saw, and what you expected to happen. Without this, we are burning cycles.

**Comment by wojtek-t** [comment]
OK - I'm able to reproduce the failure with the following code:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:use_ugorij#diff-45faf8d4fbe0c2f07d85c899e99fba72R1

$ go run reproduce.go ../../examples/guestbook/redis-master-service.yaml 
panic: json: expect char " but got char 6

**Comment by ugorji** [comment]
Thanks.

I had to use api.Service (not api.Node). Now my old repro works also, and I can reproduce the problem.

The issue is that it tries to decode from a string (expecting "..."), but it just saw 6379, so bombed. Let me follow up on it.

**Comment by wojtek-t** [comment]
Yes - exactly. Looking forward for some information from you...

**Comment by wojtek-t** [comment]
@ugorji - did you have a chance to look into it? Do you have an ETA for the fix?

**Comment by ugorji** [comment]
@wojtek-t Please take a look and share your results.

**Comment by wojtek-t** [comment]
Thanks - this problem seems to be fixed now.
I encountered the next one, but once I will be able to easily reproduce it, I will file another issue.

**Comment by wojtek-t** [comment]
@ugorji - I filed https://github.com/ugorji/go/issues/98 for the next issue (there is reproduction instruction there).
