### ISSUE TITLE
Some pointers are ignored by codec

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#98]
This is the next step of debugging issues with codec in Kubernetes.

The reproduction code is pretty similar to what we had before:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:use_ugorij#diff-22207499f9ab0d60831b9c388397f034R1

The data file to use is:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:use_ugorij#diff-86f0987a6f87b5bc1916774aec69faaaR1

The result for this data is that the pointer to "cider" in PodTemplate data structure is ignored by Codec.

I'm comparing data that is produced by:
- your codec
- json/encoding codec

@ugorji

**Comment by ugorji** [comment]
Previously, we only encoded Anonymous fields inline if there was no effective struct tag specified. However, Volume has the field: 

```
VolumeSource `json:",inline,omitempty"`
```

This effectively ensured that we didn't treat VolumeSource as inline.

We have changed it now to use the model from encoding/json i.e. Anonymous fields are always inline except a replacement field name is specified in the struct tag, or the field is of an Interface Type.

This works better.

**Comment by ugorji** [comment]
@wojtek-t ping

**Comment by wojtek-t** [comment]
Will take a look - thanks.

**Comment by ugorji** [comment]
P.S. If you set ErrorIfNoField=true on the Handle, then it would have errored when it saw "cinder" in the JSON and couldn't match it at the appropriate level while decoding.

**Comment by wojtek-t** [comment]
@ugorji - good to know - thanks!

I've checked and it fixed that problem. There are still two more tests failing in Kubernetes when I switch to your codec. I will try to understand them and will file another issue when I understand them.
However, the most demanding ones were fixed by this fix. Thanks!
