### ISSUE TITLE
Kubernetes: Decode doesn't do a case-insensitive search for key name: doesn't accept "IP" when struct tag is "ip"

### ISSUE THREAD

**Issue by wojtek-t** [ugorji/go#99]
The next issue with Kubernetes.

To reproduce:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:use_ugorij#diff-22207499f9ab0d60831b9c388397f034R1

Problematic file:
https://github.com/kubernetes/kubernetes/blob/master/examples/glusterfs/glusterfs-endpoints.json

What happens is that after unmarshaling, the IP address is empty (using encoding json is read correctly).

**Comment by wojtek-t** [comment]
@ugorji

**Comment by wojtek-t** [comment]
Please hold on a bit - this seems like a bug in Kubernetes.

It should be "ip" instead of "IP" in that json file. I don't know why it works using standard "encoding/json" library...

**Comment by ugorji** [comment]
@wojtek-t It seems encoding/json supports a case-insensitive match during decoding. That will not be supported in codec, because it impacts performance optimizations we like to make. I suggest that Kubernetes updates its JSON to use the "ip" specified in the struct tag.

**Comment by wojtek-t** [comment]
I'm fine with codec not supporting it (in fact it's misleading that encoding/json supports it).
I already created a PR fixing that in Kubernetes.
Thanks!
